// Motor de cálculo Realizado / Ano Anterior (port Base44 actualCalc.js).
// Diferente da Meta: não usa PAR — só IND oficiais.

export const ACTUAL_MANUAL_CODES = [
  'SALES_WALKIN', 'SALES_REFERRAL', 'SALES_COMPANY_PORTFOLIO', 'SALES_SELLER_PORTFOLIO',
  'SALES_INTERNET', 'SALES_OTHER', 'SELLER_COUNT', 'VEHICLES_APPRAISED', 'SALES_WITH_TRADE',
  'APPROVED_CREDIT_APPLICATIONS', 'PAID_CREDIT_APPLICATIONS', 'APPOINTMENTS_VOLUME', 'VISITS_VOLUME',
  'LEADS_RECEIVED', 'INTERNET_INVESTMENT', 'INSTAGRAM_FOLLOWERS', 'GOOGLE_BUSINESS_RATING', 'CONTENT_QUALITY',
  'ACTIVE_INVENTORY', 'INVENTORY_TOTAL', 'INVENTORY_OVER_90_VOLUME', 'INVENTORY_AVERAGE_TICKET', 'INVENTORY_AVERAGE_MARGIN',
  'CONTRIBUTION_MARGIN', 'ADDITIONAL_REVENUE', 'TOTAL_EXPENSE',
  'AVERAGE_PREPARATION_COST', 'AVERAGE_AFTER_SALES_COST', 'AFTER_SALES_VOLUME',
  'EMPLOYEE_COUNT',
] as const

/** 15 derivados do Realizado/AA — somente IND, sem PAR. */
export const ACTUAL_CALCULATED: Record<string, string> = {
  SALES_TOTAL: 'IND("SALES_WALKIN") + IND("SALES_REFERRAL") + IND("SALES_COMPANY_PORTFOLIO") + IND("SALES_SELLER_PORTFOLIO") + IND("SALES_INTERNET") + IND("SALES_OTHER")',
  SALES_PER_SELLER: 'IND("SALES_TOTAL") / IND("SELLER_COUNT")',
  LEADS_PER_SELLER: 'IND("LEADS_RECEIVED") / IND("SELLER_COUNT")',
  TRADE_SALES_PERCENTAGE: 'IND("SALES_WITH_TRADE") / IND("SALES_TOTAL")',
  FINANCED_SALES_PERCENTAGE: 'IND("PAID_CREDIT_APPLICATIONS") / IND("SALES_TOTAL")',
  APPOINTMENTS_PER_INTERNET_SALE: 'IND("APPOINTMENTS_VOLUME") / IND("SALES_INTERNET")',
  LEAD_TO_APPOINTMENT_CONVERSION: 'IND("APPOINTMENTS_VOLUME") / IND("LEADS_RECEIVED")',
  APPOINTMENT_TO_VISIT_CONVERSION: 'IND("VISITS_VOLUME") / IND("APPOINTMENTS_VOLUME")',
  VISIT_TO_SALE_CONVERSION: 'IND("SALES_INTERNET") / IND("VISITS_VOLUME")',
  INTERNET_COST_PER_SALE: 'IND("INTERNET_INVESTMENT") / IND("SALES_INTERNET")',
  INVENTORY_TURNOVER: 'IND("SALES_TOTAL") / IND("INVENTORY_TOTAL")',
  INVENTORY_OVER_90_PERCENTAGE: 'IND("INVENTORY_OVER_90_VOLUME") / IND("INVENTORY_TOTAL")',
  NET_PROFIT: 'IND("CONTRIBUTION_MARGIN") + IND("ADDITIONAL_REVENUE") - IND("TOTAL_EXPENSE")',
  AVERAGE_SALES_MARGIN: 'IND("CONTRIBUTION_MARGIN") / IND("SALES_TOTAL")',
  AFTER_SALES_PERCENTAGE: 'IND("AFTER_SALES_VOLUME") / IND("SALES_TOTAL")',
}

export const ACTUAL_BLANK_POLICY: Record<string, 'ZERO_IF_EMPTY'> = {
  SALES_OTHER: 'ZERO_IF_EMPTY',
}

export function isActualCalculated(code: string): boolean {
  return Object.prototype.hasOwnProperty.call(ACTUAL_CALCULATED, code)
}

export function isActualManual(code: string): boolean {
  return !isActualCalculated(code)
}

export function actualFormulaFor(code: string): string | null {
  return ACTUAL_CALCULATED[code] ?? null
}
