/* eslint-disable */
/**
 * GERADO AUTOMATICAMENTE — NÃO EDITE À MÃO.
 *
 * Fonte:  rules/mentor-comercial/v1/statuses.json
 * SHA256: 3268de238076e64f0f0189e96033ea3c423c6afe93d276b700fe750915d7be8e
 * Gerar:  node scripts/mentor-rules-bundle.mjs
 *
 * Contém apenas os campos que a Carteira consulta no render. O catálogo completo,
 * com definições e observações, vive em public.mentor_status_definitions.
 */

export type StatusCatalogEntry = {
  statusId: string | null
  channel: string | null
  family: string | null
  label: string | null
  responsible: string | null
  temperature: string | null
  objective: string | null
  nextStep: string | null
  cadenceId: string | null
  scriptId: string | null
  potential: string | null
  centralRule: string | null
  mentorGuidance: string | null
}

export const RULE_VERSION = "v1"
export const SOURCE_SHA256 = "3268de238076e64f0f0189e96033ea3c423c6afe93d276b700fe750915d7be8e"

export const STATUS_CATALOG: readonly StatusCatalogEntry[] = [
  {"statusId":"INT-C01","channel":"Internet","family":"Contato","label":"Primeiro contato pendente","responsible":"Vendedor","temperature":"Morno","objective":"Iniciar conversa","nextStep":"Enviar primeira abordagem","cadenceId":"CAD-01","scriptId":"SCR-INT-CAD01-T1","potential":"Baixo","centralRule":"Próxima ação hoje","mentorGuidance":"O objetivo é iniciar conversa sem parecer cobrança."},
  {"statusId":"INT-C02","channel":"Internet","family":"Contato","label":"Sem resposta — cadência ativa","responsible":"Cliente","temperature":"Morno/Frio","objective":"Iniciar conversa","nextStep":"Executar tentativa atual","cadenceId":"CAD-01","scriptId":"SCR-INT-CAD01-T{n}","potential":"Baixo","centralRule":"Tentativa da cadência vence hoje","mentorGuidance":"Execute a próxima tentativa sem mudar o status se o cliente não respondeu."},
  {"statusId":"INT-C03","channel":"Internet","family":"Contato","label":"Resposta recebida — atendimento pendente","responsible":"Vendedor","temperature":"Morno","objective":"Entender a situação","nextStep":"Responder e atualizar status","cadenceId":"Ação imediata","scriptId":"SCR-QUAL-01","potential":"Médio","centralRule":"Imediatamente/Hoje","mentorGuidance":"Cliente respondeu: a bola está com o vendedor."},
  {"statusId":"INT-C04","channel":"Internet","family":"Contato","label":"Contato inválido","responsible":"Vendedor","temperature":"-","objective":"Validar contato","nextStep":"Corrigir telefone ou confirmar impossibilidade","cadenceId":"Verificação única","scriptId":"SCR-INTERNO","potential":"Baixo","centralRule":"Quando informado","mentorGuidance":"Confirme se existe outro número antes de encerrar."},
  {"statusId":"INT-C05","channel":"Internet","family":"Contato","label":"Cliente não deseja contato","responsible":"Encerrado","temperature":"-","objective":"Respeitar solicitação","nextStep":"Encerrar contato","cadenceId":"Sem cadência","scriptId":"SCR-INTERNO","potential":"Baixo","centralRule":"Não entra","mentorGuidance":"Não insistir. Preservar histórico."},
  {"statusId":"INT-C06","channel":"Internet","family":"Contato","label":"Cadência concluída sem resposta","responsible":"Encerrado","temperature":"Frio","objective":"Preservar oportunidade","nextStep":"Retirar da Carteira Ativa","cadenceId":"Sem ação imediata","scriptId":"SCR-INTERNO","potential":"Baixo","centralRule":"Não entra","mentorGuidance":"Cliente sai da rotina diária, mas pode virar missão futura."},
  {"statusId":"INT-Q01","channel":"Internet","family":"Qualificação","label":"Qualificação inicial pendente","responsible":"Vendedor","temperature":"Morno","objective":"Entender necessidade","nextStep":"Perguntar uso e prazo","cadenceId":"CAD-04","scriptId":"SCR-QUAL-01","potential":"Médio","centralRule":"Próxima ação hoje","mentorGuidance":"Antes de falar de preço, entenda uso, prazo e necessidade."},
  {"statusId":"INT-Q02","channel":"Internet","family":"Qualificação","label":"Veículo ainda não definido","responsible":"Vendedor","temperature":"Morno","objective":"Definir solução","nextStep":"Identificar modelo, categoria e faixa","cadenceId":"CAD-04","scriptId":"SCR-QUAL-02","potential":"Médio","centralRule":"Tentativa vence hoje","mentorGuidance":"Ajude o cliente a escolher antes de pressionar por visita."},
  {"statusId":"INT-Q03","channel":"Internet","family":"Qualificação","label":"Veículo definido — condição não qualificada","responsible":"Vendedor","temperature":"Morno","objective":"Entender viabilidade","nextStep":"Perguntar prazo, troca e financiamento","cadenceId":"CAD-04","scriptId":"SCR-QUAL-03","potential":"Médio","centralRule":"Tentativa vence hoje","mentorGuidance":"Complete a qualificação para saber o melhor próximo passo."},
  {"statusId":"INT-Q04","channel":"Internet","family":"Qualificação","label":"Cliente qualificado sem visita","responsible":"Vendedor","temperature":"Quente","objective":"Gerar visita","nextStep":"Convidar para visita","cadenceId":"CAD-02","scriptId":"SCR-VISITA-CAD02-T1","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Transforme a qualificação em compromisso presencial."},
  {"statusId":"INT-Q05","channel":"Internet","family":"Qualificação","label":"Compra planejada para o futuro","responsible":"Data","temperature":"Frio/Morno","objective":"Preservar oportunidade","nextStep":"Programar data de retomada","cadenceId":"CAD-12","scriptId":"SCR-FUTURO-01","potential":"Baixo","centralRule":"Quando a data chegar","mentorGuidance":"Não force agora. Programe o retorno para o momento certo."},
  {"statusId":"INT-Q06","channel":"Internet","family":"Qualificação","label":"Aguardando veículo compatível","responsible":"Loja","temperature":"Morno","objective":"Encontrar produto","nextStep":"Registrar critérios e criar alerta","cadenceId":"Verificação periódica","scriptId":"SCR-INTERNO","potential":"Médio","centralRule":"Quando veículo compatível surgir","mentorGuidance":"Defina critérios claros para não perder a oportunidade."},
  {"statusId":"INT-Q07","channel":"Internet","family":"Qualificação","label":"Interesse enfraquecido","responsible":"Vendedor","temperature":"Frio","objective":"Definir continuidade","nextStep":"Confirmar se ainda deseja acompanhamento","cadenceId":"CAD-03","scriptId":"SCR-REATIVACAO-CAD03-T1","potential":"Baixo","centralRule":"Tentativa vence hoje","mentorGuidance":"Descubra se há oportunidade real ou se deve programar futuro."},
  {"statusId":"INT-Q08","channel":"Internet","family":"Qualificação","label":"Cliente quente sem visita","responsible":"Vendedor","temperature":"Quente","objective":"Gerar visita","nextStep":"Convidar para visita","cadenceId":"CAD-02","scriptId":"SCR-VISITA-CAD02-T1","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Cliente tem intenção. O próximo avanço é presença na loja."},
  {"statusId":"INT-V01","channel":"Internet","family":"Visita","label":"Data da visita em definição","responsible":"Vendedor/Cliente","temperature":"Quente","objective":"Definir compromisso","nextStep":"Oferecer duas opções de horário","cadenceId":"CAD-05","scriptId":"SCR-VISITA-DATA-T1","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Não deixe o aceite sem data; transforme intenção em agenda."},
  {"statusId":"INT-V02","channel":"Internet","family":"Visita","label":"Visita agendada","responsible":"Data","temperature":"Quente","objective":"Preservar compromisso","nextStep":"Aguardar janela de confirmação","cadenceId":"Derivada pela data","scriptId":"SCR-CONFIRMAR-D2","potential":"Alto","centralRule":"Somente quando entrar D-2/D-1/D0","mentorGuidance":"Visita futura cadastrada fortalece a carteira, mas só vira Central no dia/janela certa."},
  {"statusId":"INT-V03","channel":"Internet","family":"Visita","label":"Visita a confirmar","responsible":"Vendedor","temperature":"Quente","objective":"Confirmar visita","nextStep":"Confirmar visita","cadenceId":"CAD-06","scriptId":"SCR-CONFIRMAR-D1","potential":"Alto","centralRule":"Hoje","mentorGuidance":"Proteja o comparecimento. Cliente marcado e não confirmado é risco."},
  {"statusId":"INT-V04","channel":"Internet","family":"Visita","label":"Visita confirmada","responsible":"Cliente/Data","temperature":"Quente","objective":"Preparar atendimento","nextStep":"Aguardar data","cadenceId":"Derivada","scriptId":"SCR-CONFIRMAR-D0","potential":"Alto","centralRule":"Quando for hoje","mentorGuidance":"Prepare o atendimento e mantenha o compromisso vivo."},
  {"statusId":"INT-V05","channel":"Internet","family":"Visita","label":"Visita hoje","responsible":"Vendedor","temperature":"Quente","objective":"Realizar atendimento","nextStep":"Recepcionar cliente","cadenceId":"Central de Execução","scriptId":"SCR-VISITA-HOJE","potential":"Muito alto","centralRule":"Hoje","mentorGuidance":"Prioridade do dia: atender e registrar o desfecho."},
  {"statusId":"INT-V06","channel":"Internet","family":"Visita","label":"Visita cancelada pelo cliente","responsible":"Vendedor","temperature":"Morno/Quente","objective":"Recuperar compromisso","nextStep":"Reagendar","cadenceId":"CAD-07","scriptId":"SCR-NAO-COMPARECEU-T1","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Cancelamento não é perda. Recupere rapidamente."},
  {"statusId":"INT-V07","channel":"Internet","family":"Visita","label":"Cliente não compareceu","responsible":"Vendedor","temperature":"Morno/Quente","objective":"Recuperar visita","nextStep":"Abordar e reagendar","cadenceId":"CAD-07","scriptId":"SCR-NAO-COMPARECEU-T1","potential":"Alto","centralRule":"Hoje","mentorGuidance":"Recuperar rápido aumenta chance de nova visita."},
  {"statusId":"INT-V08","channel":"Internet","family":"Visita","label":"Visita realizada — desfecho pendente","responsible":"Vendedor","temperature":"Quente","objective":"Registrar avanço","nextStep":"Informar resultado do atendimento","cadenceId":"Ação no mesmo dia","scriptId":"SCR-POS-VISITA-01","potential":"Muito alto","centralRule":"Hoje","mentorGuidance":"O atendimento sem desfecho registrado vira oportunidade perdida."},
  {"statusId":"INT-N01","channel":"Internet","family":"Negociação","label":"Proposta pendente de envio","responsible":"Vendedor","temperature":"Quente","objective":"Entregar condição","nextStep":"Preparar e enviar proposta","cadenceId":"Hoje","scriptId":"SCR-PROPOSTA-ENVIAR","potential":"Muito alto","centralRule":"Hoje","mentorGuidance":"Proposta solicitada precisa de resposta rápida."},
  {"statusId":"INT-N02","channel":"Internet","family":"Negociação","label":"Proposta enviada — prazo ativo","responsible":"Cliente","temperature":"Quente","objective":"Acompanhar decisão","nextStep":"Programar retorno","cadenceId":"CAD-03","scriptId":"SCR-PROPOSTA-CAD03-T1","potential":"Alto","centralRule":"Retorno vence hoje","mentorGuidance":"Não deixe proposta sem retorno definido."},
  {"statusId":"INT-N03","channel":"Internet","family":"Negociação","label":"Proposta sem retorno","responsible":"Vendedor","temperature":"Quente","objective":"Recuperar decisão","nextStep":"Retomar proposta","cadenceId":"CAD-03","scriptId":"SCR-PROPOSTA-CAD03-T1","potential":"Alto","centralRule":"Hoje","mentorGuidance":"Retome a proposta para descobrir o ponto de trava."},
  {"statusId":"INT-N04","channel":"Internet","family":"Negociação","label":"Negociação ativa — bloqueador não definido","responsible":"Vendedor/Cliente","temperature":"Quente","objective":"Identificar obstáculo","nextStep":"Atualizar o que falta","cadenceId":"Ação imediata","scriptId":"SCR-DECISAO-01","potential":"Muito alto","centralRule":"Hoje","mentorGuidance":"Não deixe 'em negociação' genérico; defina o bloqueador real."},
  {"statusId":"INT-N05","channel":"Internet","family":"Negociação","label":"Objeção de preço","responsible":"Vendedor","temperature":"Quente","objective":"Trabalhar percepção de valor","nextStep":"Entender diferença esperada","cadenceId":"CAD-03","scriptId":"SCR-OBJECAO-PRECO","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Trabalhe valor, não prometa desconto inexistente."},
  {"statusId":"INT-N06","channel":"Internet","family":"Negociação","label":"Objeção de entrada","responsible":"Vendedor","temperature":"Quente","objective":"Buscar viabilidade","nextStep":"Entender entrada possível","cadenceId":"CAD-03","scriptId":"SCR-OBJECAO-ENTRADA","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Descubra qual entrada cabe antes de refazer condição."},
  {"statusId":"INT-N07","channel":"Internet","family":"Negociação","label":"Objeção de parcela","responsible":"Vendedor","temperature":"Quente","objective":"Ajustar estrutura","nextStep":"Entender parcela e prazo viáveis","cadenceId":"CAD-03","scriptId":"SCR-OBJECAO-PARCELA","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Entenda parcela alvo sem prometer aprovação."},
  {"statusId":"INT-N08","channel":"Internet","family":"Negociação","label":"Comparando veículos ou concorrentes","responsible":"Cliente","temperature":"Quente","objective":"Diferenciar solução","nextStep":"Entender critérios de comparação","cadenceId":"CAD-03","scriptId":"SCR-COMPARACAO-01","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Descubra critérios da comparação para reposicionar a solução."},
  {"statusId":"INT-N09","channel":"Internet","family":"Negociação","label":"Aguardando decisão do cliente","responsible":"Cliente","temperature":"Quente","objective":"Recuperar decisão","nextStep":"Follow-up consultivo","cadenceId":"CAD-03","scriptId":"SCR-DECISAO-CAD03-T1","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Pergunte o que pesa na decisão; não cobre resposta vazia."},
  {"statusId":"INT-N10","channel":"Internet","family":"Negociação","label":"Aguardando decisão de terceiro","responsible":"Terceiro","temperature":"Quente","objective":"Envolver decisor","nextStep":"Facilitar participação","cadenceId":"CAD-10","scriptId":"SCR-TERCEIRO-01","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Ajude a envolver quem decide para evitar perda silenciosa."},
  {"statusId":"INT-N11","channel":"Internet","family":"Negociação","label":"Aguardando condição da loja","responsible":"Loja","temperature":"Quente","objective":"Obter resposta interna","nextStep":"Cobrar decisão interna","cadenceId":"CAD-11","scriptId":"SCR-INTERNO","potential":"Muito alto","centralRule":"Verificação interna hoje","mentorGuidance":"Não cobre o cliente enquanto a pendência é interna."},
  {"statusId":"INT-N12","channel":"Internet","family":"Negociação","label":"Pronto para fechamento","responsible":"Vendedor","temperature":"Quente","objective":"Formalizar venda","nextStep":"Confirmar aceite e próximos dados","cadenceId":"Imediata","scriptId":"SCR-FECHAMENTO-01","potential":"Muito alto","centralRule":"Hoje","mentorGuidance":"Não deixe fechamento esfriar; formalize o compromisso."},
  {"statusId":"POR-A01","channel":"Porta","family":"Visita","label":"Atendimento espontâneo em andamento","responsible":"Vendedor","temperature":"Quente","objective":"Realizar atendimento","nextStep":"Diagnosticar e apresentar solução","cadenceId":"Sem cadência","scriptId":"SCR-INTERNO","potential":"Muito alto","centralRule":"Não entra enquanto em atendimento","mentorGuidance":"Atenda e registre apenas o que importa."},
  {"statusId":"POR-A02","channel":"Porta","family":"Visita","label":"Atendimento concluído — desfecho pendente","responsible":"Vendedor","temperature":"Quente","objective":"Registrar resultado","nextStep":"Informar o que aconteceu","cadenceId":"Mesmo dia","scriptId":"SCR-INTERNO","potential":"Muito alto","centralRule":"Hoje","mentorGuidance":"Sem desfecho, a gestão perde a oportunidade."},
  {"statusId":"POR-A03","channel":"Porta","family":"Negociação","label":"Visitou e não comprou","responsible":"Vendedor","temperature":"Quente","objective":"Manter negociação viva","nextStep":"Enviar resumo e retomar conversa","cadenceId":"CAD-03","scriptId":"SCR-POS-VISITA-01","potential":"Alto","centralRule":"Hoje","mentorGuidance":"A visita já aconteceu; agora o foco é recuperar decisão."},
  {"statusId":"POR-A04","channel":"Porta","family":"Negociação","label":"Pós-visita sem resposta","responsible":"Cliente","temperature":"Morno/Quente","objective":"Recuperar oportunidade","nextStep":"Executar tentativa de follow-up","cadenceId":"CAD-03","scriptId":"SCR-POS-VISITA-CAD03-T{n}","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Cliente que visitou tem valor maior que lead frio."},
  {"statusId":"CAR-C01","channel":"Carteira","family":"Contato","label":"Indicação recebida — contato pendente","responsible":"Vendedor","temperature":"Morno","objective":"Iniciar conversa","nextStep":"Abordar mencionando a indicação","cadenceId":"CAD-01","scriptId":"SCR-CAR-INDICACAO-01","potential":"Médio","centralRule":"Próxima ação hoje","mentorGuidance":"Use a indicação como ponte de confiança."},
  {"statusId":"CAR-C02","channel":"Carteira","family":"Contato","label":"Prospecção própria — contato pendente","responsible":"Vendedor","temperature":"Morno","objective":"Iniciar conversa","nextStep":"Executar abordagem de prospecção","cadenceId":"CAD-01","scriptId":"SCR-CAR-PROSPECCAO-01","potential":"Médio","centralRule":"Próxima ação hoje","mentorGuidance":"O motivo real do contato deve estar claro."},
  {"statusId":"CAR-C03","channel":"Carteira","family":"Contato","label":"Cliente antigo — reativação pendente","responsible":"Vendedor","temperature":"Frio/Morno","objective":"Retomar relacionamento","nextStep":"Fazer abordagem de reativação","cadenceId":"CAD-03","scriptId":"SCR-CAR-REATIVACAO-T1","potential":"Médio","centralRule":"Tentativa vence hoje","mentorGuidance":"Retomar histórico antes de tentar vender."},
  {"statusId":"CAR-C04","channel":"Carteira","family":"Contato","label":"Lead antigo acima de 90 dias","responsible":"Vendedor","temperature":"Frio/Morno","objective":"Reativar oportunidade","nextStep":"Retomar com novo contexto","cadenceId":"CAD-03","scriptId":"SCR-CAR-REATIVACAO-T1","potential":"Médio","centralRule":"Tentativa vence hoje","mentorGuidance":"Preserve canalEntrada original e canalVenda Carteira se vender."},
  {"statusId":"CAR-C05","channel":"Carteira","family":"Contato","label":"Contato de anúncio próprio","responsible":"Vendedor","temperature":"Morno","objective":"Iniciar conversa","nextStep":"Responder e qualificar","cadenceId":"CAD-01","scriptId":"SCR-CAR-PROSPECCAO-01","potential":"Médio","centralRule":"Próxima ação hoje","mentorGuidance":"Origem detalhada: marketplace/OLX/tráfego próprio."},
  {"statusId":"CAR-C06","channel":"Carteira","family":"Qualificação","label":"Cliente procurou diretamente o vendedor","responsible":"Vendedor","temperature":"Morno/Quente","objective":"Qualificar intenção","nextStep":"Entender necessidade e prazo","cadenceId":"CAD-04","scriptId":"SCR-QUAL-01","potential":"Médio","centralRule":"Hoje","mentorGuidance":"Aproveite confiança existente para qualificar rápido."},
  {"statusId":"CAR-C07","channel":"Carteira","family":"Relacionamento","label":"Oportunidade de troca ativada","responsible":"Vendedor","temperature":"Morno/Quente","objective":"Criar nova compra","nextStep":"Entender intenção de troca","cadenceId":"CAD-04","scriptId":"SCR-TROCA-FUTURA-01","potential":"Médio","centralRule":"Na data de ativação","mentorGuidance":"Transforme relacionamento em nova oportunidade."},
  {"statusId":"CAR-C08","channel":"Carteira","family":"Relacionamento","label":"Cliente de pós-venda com potencial","responsible":"Vendedor","temperature":"Morno","objective":"Gerar nova oportunidade","nextStep":"Conversar sobre momento atual","cadenceId":"CAD-04","scriptId":"SCR-POSVENDA-01","potential":"Médio","centralRule":"Quando marco vence","mentorGuidance":"Pós-venda bem feito pode gerar indicação ou recompra."},
  {"statusId":"TR-01","channel":"Compartilhado","family":"Troca","label":"Aguardando dados do carro da troca","responsible":"Cliente","temperature":"Quente","objective":"Obter informações","nextStep":"Solicitar placa, versão, ano, km e fotos","cadenceId":"CAD-08","scriptId":"SCR-TROCA-DADOS-T1","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Solicite dados antes de estimar valor."},
  {"statusId":"TR-02","channel":"Compartilhado","family":"Troca","label":"Dados recebidos — avaliação pendente","responsible":"Loja","temperature":"Quente","objective":"Conseguir avaliação","nextStep":"Encaminhar para avaliação","cadenceId":"CAD-11","scriptId":"SCR-INTERNO","potential":"Alto","centralRule":"Verificação interna hoje","mentorGuidance":"A pendência agora é interna, não do cliente."},
  {"statusId":"TR-03","channel":"Compartilhado","family":"Troca","label":"Avaliação presencial necessária","responsible":"Vendedor/Cliente","temperature":"Quente","objective":"Levar veículo à loja","nextStep":"Agendar avaliação presencial","cadenceId":"CAD-02","scriptId":"SCR-VISITA-CAD02-T1","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Agora sim o próximo passo é agendar visita/avaliação."},
  {"statusId":"TR-04","channel":"Compartilhado","family":"Troca","label":"Avaliação em andamento","responsible":"Loja","temperature":"Quente","objective":"Concluir avaliação","nextStep":"Verificar internamente","cadenceId":"CAD-11","scriptId":"SCR-INTERNO","potential":"Alto","centralRule":"Verificação interna hoje","mentorGuidance":"Não cobre o cliente enquanto a loja avalia."},
  {"statusId":"TR-05","channel":"Compartilhado","family":"Troca","label":"Avaliação concluída — valor não apresentado","responsible":"Vendedor","temperature":"Quente","objective":"Apresentar condição","nextStep":"Enviar ou apresentar avaliação","cadenceId":"Hoje","scriptId":"SCR-TROCA-VALOR-01","potential":"Muito alto","centralRule":"Hoje","mentorGuidance":"Valor pronto precisa ser apresentado rapidamente."},
  {"statusId":"TR-06","channel":"Compartilhado","family":"Troca","label":"Valor apresentado — aguardando cliente","responsible":"Cliente","temperature":"Quente","objective":"Conseguir aceite","nextStep":"Retomar decisão da troca","cadenceId":"CAD-03","scriptId":"SCR-TROCA-VALOR-01","potential":"Alto","centralRule":"Retorno vence hoje","mentorGuidance":"Troca pode ser o bloqueador central da venda."},
  {"statusId":"TR-07","channel":"Compartilhado","family":"Troca","label":"Cliente não aceitou a avaliação","responsible":"Vendedor","temperature":"Quente","objective":"Tratar objeção","nextStep":"Entender valor esperado e diferença","cadenceId":"CAD-03","scriptId":"SCR-TROCA-OBJECAO-01","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Entenda a expectativa antes de negociar condição."},
  {"statusId":"TR-08","channel":"Compartilhado","family":"Troca","label":"Troca aprovada","responsible":"Sistema","temperature":"Quente","objective":"Retomar negociação principal","nextStep":"Verificar próximo bloqueador","cadenceId":"Automática","scriptId":"SCR-INTERNO","potential":"Muito alto","centralRule":"Se houver próximo passo hoje","mentorGuidance":"Troca deixou de bloquear. Avance para fechamento ou próxima pendência."},
  {"statusId":"TR-09","channel":"Compartilhado","family":"Troca","label":"Troca inviável","responsible":"Loja/Vendedor","temperature":"Morno/Quente","objective":"Apresentar alternativa","nextStep":"Explicar e oferecer caminho possível","cadenceId":"CAD-03","scriptId":"SCR-TROCA-INVIAVEL-01","potential":"Médio","centralRule":"Tentativa vence hoje","mentorGuidance":"Apresente alternativa sem prometer condição impossível."},
  {"statusId":"FIN-01","channel":"Compartilhado","family":"Financiamento","label":"Simulação pendente","responsible":"Vendedor","temperature":"Quente","objective":"Apresentar condição","nextStep":"Preparar simulação","cadenceId":"Hoje","scriptId":"SCR-FIN-SIMULAR-01","potential":"Alto","centralRule":"Hoje","mentorGuidance":"Simulação pedida exige resposta rápida."},
  {"statusId":"FIN-02","channel":"Compartilhado","family":"Financiamento","label":"Simulação enviada — aguardando cliente","responsible":"Cliente","temperature":"Quente","objective":"Validar condição","nextStep":"Retomar simulação","cadenceId":"CAD-03","scriptId":"SCR-FIN-SIMULACAO-CAD03-T1","potential":"Alto","centralRule":"Retorno vence hoje","mentorGuidance":"Valide entrada/parcela/prazo com cuidado."},
  {"statusId":"FIN-03","channel":"Compartilhado","family":"Financiamento","label":"Documentos para ficha pendentes","responsible":"Cliente","temperature":"Quente","objective":"Completar ficha","nextStep":"Solicitar documentos","cadenceId":"CAD-08","scriptId":"SCR-FIN-DOCUMENTOS-T1","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Peça apenas documentos realmente necessários."},
  {"statusId":"FIN-04","channel":"Compartilhado","family":"Financiamento","label":"Ficha em análise","responsible":"Financeira","temperature":"Quente","objective":"Obter retorno","nextStep":"Verificar análise","cadenceId":"CAD-11","scriptId":"SCR-INTERNO","potential":"Alto","centralRule":"Verificação interna hoje","mentorGuidance":"Pendência é financeira; mantenha cliente informado com base real."},
  {"statusId":"FIN-05","channel":"Compartilhado","family":"Financiamento","label":"Pendência solicitada pela financeira","responsible":"Cliente/Vendedor","temperature":"Quente","objective":"Completar análise","nextStep":"Solicitar pendência","cadenceId":"CAD-08","scriptId":"SCR-FIN-DOCUMENTOS-T1","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"A pendência precisa ser específica e registrada."},
  {"statusId":"FIN-06","channel":"Compartilhado","family":"Financiamento","label":"Financiamento aprovado sem fechamento","responsible":"Vendedor","temperature":"Quente","objective":"Converter aprovação","nextStep":"Conduzir para fechamento","cadenceId":"CAD-09","scriptId":"SCR-FIN-APROVADO-T1","potential":"Muito alto","centralRule":"Hoje","mentorGuidance":"Aprovação reduz barreira. Prioridade alta de fechamento."},
  {"statusId":"FIN-07","channel":"Compartilhado","family":"Financiamento","label":"Aprovado com condição diferente","responsible":"Vendedor","temperature":"Quente","objective":"Reestruturar negociação","nextStep":"Apresentar condição real","cadenceId":"CAD-03","scriptId":"SCR-FIN-CONDICAO-DIFERENTE-01","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Explique condição real sem prometer o que não existe."},
  {"statusId":"FIN-08","channel":"Compartilhado","family":"Financiamento","label":"Financiamento recusado","responsible":"Vendedor","temperature":"Morno","objective":"Avaliar alternativa","nextStep":"Verificar outro caminho autorizado","cadenceId":"Imediata","scriptId":"SCR-FIN-RECUSADO-01","potential":"Médio","centralRule":"Hoje","mentorGuidance":"Tratar com cuidado e buscar alternativas viáveis."},
  {"statusId":"FIN-09","channel":"Compartilhado","family":"Financiamento","label":"Nova simulação necessária","responsible":"Vendedor","temperature":"Quente","objective":"Ajustar estrutura","nextStep":"Refazer simulação","cadenceId":"Hoje","scriptId":"SCR-FIN-SIMULAR-01","potential":"Alto","centralRule":"Hoje","mentorGuidance":"Refazer condição apenas com dados reais."},
  {"statusId":"VEN-01","channel":"Compartilhado","family":"Venda e Entrega","label":"Venda acordada — formalização pendente","responsible":"Vendedor","temperature":"Quente","objective":"Formalizar negócio","nextStep":"Confirmar dados e processo","cadenceId":"Hoje","scriptId":"SCR-FECHAMENTO-01","potential":"Muito alto","centralRule":"Hoje","mentorGuidance":"Formalize para não deixar o aceite esfriar."},
  {"statusId":"VEN-02","channel":"Compartilhado","family":"Venda e Entrega","label":"Sinal pendente","responsible":"Cliente","temperature":"Quente","objective":"Confirmar compromisso","nextStep":"Orientar pagamento do sinal","cadenceId":"CAD-08","scriptId":"SCR-SINAL-01","potential":"Muito alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Sinal pendente precisa de acompanhamento rápido."},
  {"statusId":"VEN-03","channel":"Compartilhado","family":"Venda e Entrega","label":"Sinal recebido — fechamento pendente","responsible":"Loja/Vendedor","temperature":"Quente","objective":"Concluir venda","nextStep":"Finalizar formalização","cadenceId":"Hoje","scriptId":"SCR-INTERNO","potential":"Muito alto","centralRule":"Hoje","mentorGuidance":"Sinal pago aumenta responsabilidade de fechamento."},
  {"statusId":"VEN-04","channel":"Compartilhado","family":"Venda e Entrega","label":"Venda realizada","responsible":"Sistema","temperature":"-","objective":"Registrar resultado","nextStep":"Alimentar funil, faturamento e histórico","cadenceId":"Automática","scriptId":"SCR-INTERNO","potential":"-","centralRule":"Não entra, salvo próximo passo configurado","mentorGuidance":"Venda concluída. Ativar pós-venda se loja usar."},
  {"statusId":"VEN-05","channel":"Compartilhado","family":"Venda e Entrega","label":"Entrega agendada","responsible":"Data/Vendedor","temperature":"-","objective":"Preparar entrega","nextStep":"Aguardar data","cadenceId":"Derivada","scriptId":"SCR-ENTREGA-01","potential":"Médio","centralRule":"Quando data for hoje","mentorGuidance":"Só criar entrega se loja atribui isso ao vendedor."},
  {"statusId":"VEN-06","channel":"Compartilhado","family":"Venda e Entrega","label":"Entrega hoje","responsible":"Vendedor","temperature":"-","objective":"Realizar entrega","nextStep":"Executar entrega","cadenceId":"Central","scriptId":"SCR-ENTREGA-01","potential":"Médio","centralRule":"Hoje","mentorGuidance":"Entrega pode ser oportunidade de relacionamento."},
  {"statusId":"VEN-07","channel":"Compartilhado","family":"Venda e Entrega","label":"Veículo entregue","responsible":"Sistema","temperature":"-","objective":"Iniciar relacionamento","nextStep":"Ativar pós-venda se configurado","cadenceId":"Automática","scriptId":"SCR-POSVENDA-D7","potential":"Médio","centralRule":"Conforme pós-venda","mentorGuidance":"Ativar relacionamento sem obrigar loja que não usa pós-venda."},
  {"statusId":"PER-01","channel":"Compartilhado","family":"Perda e Futuro","label":"Motivo da perda pendente","responsible":"Vendedor","temperature":"-","objective":"Qualificar perda","nextStep":"Registrar motivo","cadenceId":"Hoje","scriptId":"SCR-INTERNO","potential":"Baixo","centralRule":"Hoje","mentorGuidance":"Sem motivo de perda, a carteira perde inteligência."},
  {"statusId":"PER-02","channel":"Compartilhado","family":"Perda e Futuro","label":"Venda perdida","responsible":"Encerrado","temperature":"-","objective":"Preservar inteligência","nextStep":"Encerrar oportunidade","cadenceId":"Sem cadência","scriptId":"SCR-INTERNO","potential":"Baixo","centralRule":"Não entra","mentorGuidance":"Perda qualificada pode virar oportunidade futura."},
  {"statusId":"PER-03","channel":"Compartilhado","family":"Perda e Futuro","label":"Cadência encerrada sem resposta","responsible":"Encerrado","temperature":"Frio","objective":"Preservar cliente","nextStep":"Retirar da Carteira Ativa","cadenceId":"Sem ação","scriptId":"SCR-INTERNO","potential":"Baixo","centralRule":"Não entra","mentorGuidance":"Não é perda automática; vira base para Plano de Ataque."},
  {"statusId":"PER-04","channel":"Compartilhado","family":"Perda e Futuro","label":"Contato inválido encerrado","responsible":"Encerrado","temperature":"-","objective":"Evitar esforço improdutivo","nextStep":"Encerrar","cadenceId":"Sem cadência","scriptId":"SCR-INTERNO","potential":"Baixo","centralRule":"Não entra","mentorGuidance":"Preservar histórico e evitar novas tentativas inúteis."},
  {"statusId":"PER-05","channel":"Compartilhado","family":"Perda e Futuro","label":"Contato futuro programado","responsible":"Data","temperature":"Frio/Morno","objective":"Retomar no momento certo","nextStep":"Aguardar data","cadenceId":"CAD-12","scriptId":"SCR-FUTURO-01","potential":"Baixo","centralRule":"Quando data chegar","mentorGuidance":"A carteira deve lembrar no momento certo."},
  {"statusId":"PER-06","channel":"Compartilhado","family":"Perda e Futuro","label":"Oportunidade transferida para Carteira","responsible":"Sistema","temperature":"Frio/Morno","objective":"Reconhecer ação futura do vendedor","nextStep":"Criar nova oportunidade Carteira","cadenceId":"Automática","scriptId":"SCR-CAR-REATIVACAO-T1","potential":"Médio","centralRule":"Quando reativado","mentorGuidance":"Preservar canalEntrada e calcular canalVenda Carteira se vender."},
  {"statusId":"REL-01","channel":"Compartilhado","family":"Relacionamento","label":"Pós-venda D+7","responsible":"Vendedor","temperature":"-","objective":"Verificar satisfação","nextStep":"Fazer contato e pedir indicação","cadenceId":"CAD-13","scriptId":"SCR-POSVENDA-D7","potential":"Médio","centralRule":"Quando marco vence","mentorGuidance":"Relacionamento bem feito gera indicação."},
  {"statusId":"REL-02","channel":"Compartilhado","family":"Relacionamento","label":"Pós-venda D+30","responsible":"Vendedor","temperature":"-","objective":"Confirmar adaptação","nextStep":"Fazer contato","cadenceId":"CAD-13","scriptId":"SCR-POSVENDA-D30","potential":"Médio","centralRule":"Quando marco vence","mentorGuidance":"Manter relacionamento após compra."},
  {"statusId":"REL-03","channel":"Compartilhado","family":"Relacionamento","label":"Relacionamento D+180","responsible":"Vendedor","temperature":"-","objective":"Manter proximidade","nextStep":"Fazer contato leve","cadenceId":"CAD-13","scriptId":"SCR-POSVENDA-D180","potential":"Baixo","centralRule":"Quando marco vence","mentorGuidance":"Cliente antigo bem acompanhado vira Carteira."},
  {"statusId":"REL-04","channel":"Compartilhado","family":"Relacionamento","label":"Troca potencial em 12 meses","responsible":"Vendedor","temperature":"Morno","objective":"Identificar intenção","nextStep":"Conversar sobre ciclo de troca","cadenceId":"CAD-13","scriptId":"SCR-TROCA-12M","potential":"Médio","centralRule":"Quando marco vence","mentorGuidance":"Começar a preparar futura troca."},
  {"statusId":"REL-05","channel":"Compartilhado","family":"Relacionamento","label":"Oferta de troca em 18 meses","responsible":"Vendedor","temperature":"Morno/Quente","objective":"Criar oportunidade","nextStep":"Apresentar possibilidade de upgrade","cadenceId":"CAD-13","scriptId":"SCR-TROCA-18M","potential":"Médio","centralRule":"Quando marco vence","mentorGuidance":"Relacionamento vira nova venda."},
  {"statusId":"REL-06","channel":"Compartilhado","family":"Relacionamento","label":"Recompra ou troca em 24 meses","responsible":"Vendedor","temperature":"Morno/Quente","objective":"Gerar nova compra","nextStep":"Reabrir oportunidade","cadenceId":"CAD-13","scriptId":"SCR-TROCA-24M","potential":"Alto","centralRule":"Quando marco vence","mentorGuidance":"Momento ideal para nova oportunidade de Carteira."},
  {"statusId":"REL-07","channel":"Compartilhado","family":"Relacionamento","label":"Garantia aberta","responsible":"Vendedor/Loja","temperature":"-","objective":"Proteger relacionamento","nextStep":"Confirmar recebimento e orientar","cadenceId":"CAD-11","scriptId":"SCR-GARANTIA-01","potential":"Médio","centralRule":"Quando acompanhamento vence","mentorGuidance":"Garantia é relação sensível, não apenas operação."},
  {"statusId":"REL-08","channel":"Compartilhado","family":"Relacionamento","label":"Garantia em acompanhamento","responsible":"Loja/Vendedor","temperature":"-","objective":"Manter cliente informado","nextStep":"Verificar andamento","cadenceId":"CAD-11","scriptId":"SCR-GARANTIA-01","potential":"Médio","centralRule":"Quando acompanhamento vence","mentorGuidance":"Cliente precisa sentir acompanhamento."},
  {"statusId":"REL-09","channel":"Compartilhado","family":"Relacionamento","label":"Garantia resolvida","responsible":"Vendedor","temperature":"-","objective":"Recuperar confiança","nextStep":"Confirmar satisfação","cadenceId":"Hoje","scriptId":"SCR-GARANTIA-RESOLVIDA","potential":"Médio","centralRule":"Hoje","mentorGuidance":"Feche o ciclo de garantia com relacionamento."},
] as const

const PORT_INDEX = new Map(STATUS_CATALOG.map((s) => [s.statusId, s]))

export function statusPorId(statusId: string | null | undefined): StatusCatalogEntry | null {
  if (!statusId) return null
  return PORT_INDEX.get(statusId) ?? null
}
