
/**
 * GERADO AUTOMATICAMENTE — NÃO EDITE À MÃO.
 *
 * Fonte:  rules/mentor-comercial/v1/statuses.json
 * SHA256: 3268de238076e64f0f0189e96033ea3c423c6afe93d276b700fe750915d7be8e
 * Gerar:  node scripts/mentor-rules-bundle.mjs
 *
 * Contém apenas os campos que a Carteira consulta no render. O catálogo completo,
 * com definições e observações, vive em public.mentor_status_definitions.
 */

export type StatusCatalogEntry = {
  statusId: string | null
  channel: string | null
  family: string | null
  label: string | null
  responsible: string | null
  temperature: string | null
  objective: string | null
  nextStep: string | null
  cadenceId: string | null
  scriptId: string | null
  potential: string | null
  centralRule: string | null
  mentorGuidance: string | null
}

export const RULE_VERSION = "v1"
export const SOURCE_SHA256 = "3268de238076e64f0f0189e96033ea3c423c6afe93d276b700fe750915d7be8e"

export const STATUS_CATALOG: readonly StatusCatalogEntry[] = [
  {"statusId":"INT-C01","channel":"Internet","family":"Contato","label":"Primeiro contato pendente","responsible":"Vendedor","temperature":"Morno","objective":"Iniciar conversa","nextStep":"Enviar primeira abordagem","cadenceId":"CAD-01","scriptId":"SCR-INT-CAD01-T1","potential":"Baixo","centralRule":"Próxima ação hoje","mentorGuidance":"O objetivo é iniciar conversa sem parecer cobrança."},
  {"statusId":"INT-C02","channel":"Internet","family":"Contato","label":"Sem resposta — cadência ativa","responsible":"Cliente","temperature":"Morno/Frio","objective":"Iniciar conversa","nextStep":"Executar tentativa atual","cadenceId":"CAD-01","scriptId":"SCR-INT-CAD01-T{n}","potential":"Baixo","centralRule":"Tentativa da cadência vence hoje","mentorGuidance":"Execute a próxima tentativa sem mudar o status se o cliente não respondeu."},
  {"statusId":"INT-C03","channel":"Internet","family":"Contato","label":"Resposta recebida — atendimento pendente","responsible":"Vendedor","temperature":"Morno","objective":"Entender a situação","nextStep":"Responder e atualizar status","cadenceId":"Ação imediata","scriptId":"SCR-QUAL-01","potential":"Médio","centralRule":"Imediatamente/Hoje","mentorGuidance":"Cliente respondeu: a bola está com o vendedor."},
  {"statusId":"INT-C04","channel":"Internet","family":"Contato","label":"Contato inválido","responsible":"Vendedor","temperature":"-","objective":"Validar contato","nextStep":"Corrigir telefone ou confirmar impossibilidade","cadenceId":"Verificação única","scriptId":"SCR-INTERNO","potential":"Baixo","centralRule":"Quando informado","mentorGuidance":"Confirme se existe outro número antes de encerrar."},
  {"statusId":"INT-C05","channel":"Internet","family":"Contato","label":"Cliente não deseja contato","responsible":"Encerrado","temperature":"-","objective":"Respeitar solicitação","nextStep":"Encerrar contato","cadenceId":"Sem cadência","scriptId":"SCR-INTERNO","potential":"Baixo","centralRule":"Não entra","mentorGuidance":"Não insistir. Preservar histórico."},
  {"statusId":"INT-C06","channel":"Internet","family":"Contato","label":"Cadência concluída sem resposta","responsible":"Encerrado","temperature":"Frio","objective":"Preservar oportunidade","nextStep":"Retirar da Carteira Ativa","cadenceId":"Sem ação imediata","scriptId":"SCR-INTERNO","potential":"Baixo","centralRule":"Não entra","mentorGuidance":"Cliente sai da rotina diária, mas pode virar missão futura."},
  {"statusId":"INT-Q01","channel":"Internet","family":"Qualificação","label":"Qualificação inicial pendente","responsible":"Vendedor","temperature":"Morno","objective":"Entender necessidade","nextStep":"Perguntar uso e prazo","cadenceId":"CAD-04","scriptId":"SCR-QUAL-01","potential":"Médio","centralRule":"Próxima ação hoje","mentorGuidance":"Antes de falar de preço, entenda uso, prazo e necessidade."},
  {"statusId":"INT-Q02","channel":"Internet","family":"Qualificação","label":"Veículo ainda não definido","responsible":"Vendedor","temperature":"Morno","objective":"Definir solução","nextStep":"Identificar modelo, categoria e faixa","cadenceId":"CAD-04","scriptId":"SCR-QUAL-02","potential":"Médio","centralRule":"Tentativa vence hoje","mentorGuidance":"Ajude o cliente a escolher antes de pressionar por visita."},
  {"statusId":"INT-Q03","channel":"Internet","family":"Qualificação","label":"Veículo definido — condição não qualificada","responsible":"Vendedor","temperature":"Morno","objective":"Entender viabilidade","nextStep":"Perguntar prazo, troca e financiamento","cadenceId":"CAD-04","scriptId":"SCR-QUAL-03","potential":"Médio","centralRule":"Tentativa vence hoje","mentorGuidance":"Complete a qualificação para saber o melhor próximo passo."},
  {"statusId":"INT-Q04","channel":"Internet","family":"Qualificação","label":"Cliente qualificado sem visita","responsible":"Vendedor","temperature":"Quente","objective":"Gerar visita","nextStep":"Convidar para visita","cadenceId":"CAD-02","scriptId":"SCR-VISITA-CAD02-T1","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Transforme a qualificação em compromisso presencial."},
  {"statusId":"INT-Q05","channel":"Internet","family":"Qualificação","label":"Compra planejada para o futuro","responsible":"Data","temperature":"Frio/Morno","objective":"Preservar oportunidade","nextStep":"Programar data de retomada","cadenceId":"CAD-12","scriptId":"SCR-FUTURO-01","potential":"Baixo","centralRule":"Quando a data chegar","mentorGuidance":"Não force agora. Programe o retorno para o momento certo."},
  {"statusId":"INT-Q06","channel":"Internet","family":"Qualificação","label":"Aguardando veículo compatível","responsible":"Loja","temperature":"Morno","objective":"Encontrar produto","nextStep":"Registrar critérios e criar alerta","cadenceId":"Verificação periódica","scriptId":"SCR-INTERNO","potential":"Médio","centralRule":"Quando veículo compatível surgir","mentorGuidance":"Defina critérios claros para não perder a oportunidade."},
  {"statusId":"INT-Q07","channel":"Internet","family":"Qualificação","label":"Interesse enfraquecido","responsible":"Vendedor","temperature":"Frio","objective":"Definir continuidade","nextStep":"Confirmar se ainda deseja acompanhamento","cadenceId":"CAD-03","scriptId":"SCR-REATIVACAO-CAD03-T1","potential":"Baixo","centralRule":"Tentativa vence hoje","mentorGuidance":"Descubra se há oportunidade real ou se deve programar futuro."},
  {"statusId":"INT-Q08","channel":"Internet","family":"Qualificação","label":"Cliente quente sem visita","responsible":"Vendedor","temperature":"Quente","objective":"Gerar visita","nextStep":"Convidar para visita","cadenceId":"CAD-02","scriptId":"SCR-VISITA-CAD02-T1","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Cliente tem intenção. O próximo avanço é presença na loja."},
  {"statusId":"INT-V01","channel":"Internet","family":"Visita","label":"Data da visita em definição","responsible":"Vendedor/Cliente","temperature":"Quente","objective":"Definir compromisso","nextStep":"Oferecer duas opções de horário","cadenceId":"CAD-05","scriptId":"SCR-VISITA-DATA-T1","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Não deixe o aceite sem data; transforme intenção em agenda."},
  {"statusId":"INT-V02","channel":"Internet","family":"Visita","label":"Visita agendada","responsible":"Data","temperature":"Quente","objective":"Preservar compromisso","nextStep":"Aguardar janela de confirmação","cadenceId":"Derivada pela data","scriptId":"SCR-CONFIRMAR-D2","potential":"Alto","centralRule":"Somente quando entrar D-2/D-1/D0","mentorGuidance":"Visita futura cadastrada fortalece a carteira, mas só vira Central no dia/janela certa."},
  {"statusId":"INT-V03","channel":"Internet","family":"Visita","label":"Visita a confirmar","responsible":"Vendedor","temperature":"Quente","objective":"Confirmar visita","nextStep":"Confirmar visita","cadenceId":"CAD-06","scriptId":"SCR-CONFIRMAR-D1","potential":"Alto","centralRule":"Hoje","mentorGuidance":"Proteja o comparecimento. Cliente marcado e não confirmado é risco."},
  {"statusId":"INT-V04","channel":"Internet","family":"Visita","label":"Visita confirmada","responsible":"Cliente/Data","temperature":"Quente","objective":"Preparar atendimento","nextStep":"Aguardar data","cadenceId":"Derivada","scriptId":"SCR-CONFIRMAR-D0","potential":"Alto","centralRule":"Quando for hoje","mentorGuidance":"Prepare o atendimento e mantenha o compromisso vivo."},
  {"statusId":"INT-V05","channel":"Internet","family":"Visita","label":"Visita hoje","responsible":"Vendedor","temperature":"Quente","objective":"Realizar atendimento","nextStep":"Recepcionar cliente","cadenceId":"Central de Execução","scriptId":"SCR-VISITA-HOJE","potential":"Muito alto","centralRule":"Hoje","mentorGuidance":"Prioridade do dia: atender e registrar o desfecho."},
  {"statusId":"INT-V06","channel":"Internet","family":"Visita","label":"Visita cancelada pelo cliente","responsible":"Vendedor","temperature":"Morno/Quente","objective":"Recuperar compromisso","nextStep":"Reagendar","cadenceId":"CAD-07","scriptId":"SCR-NAO-COMPARECEU-T1","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Cancelamento não é perda. Recupere rapidamente."},
  {"statusId":"INT-V07","channel":"Internet","family":"Visita","label":"Cliente não compareceu","responsible":"Vendedor","temperature":"Morno/Quente","objective":"Recuperar visita","nextStep":"Abordar e reagendar","cadenceId":"CAD-07","scriptId":"SCR-NAO-COMPARECEU-T1","potential":"Alto","centralRule":"Hoje","mentorGuidance":"Recuperar rápido aumenta chance de nova visita."},
  {"statusId":"INT-V08","channel":"Internet","family":"Visita","label":"Visita realizada — desfecho pendente","responsible":"Vendedor","temperature":"Quente","objective":"Registrar avanço","nextStep":"Informar resultado do atendimento","cadenceId":"Ação no mesmo dia","scriptId":"SCR-POS-VISITA-01","potential":"Muito alto","centralRule":"Hoje","mentorGuidance":"O atendimento sem desfecho registrado vira oportunidade perdida."},
  {"statusId":"INT-N01","channel":"Internet","family":"Negociação","label":"Proposta pendente de envio","responsible":"Vendedor","temperature":"Quente","objective":"Entregar condição","nextStep":"Preparar e enviar proposta","cadenceId":"Hoje","scriptId":"SCR-PROPOSTA-ENVIAR","potential":"Muito alto","centralRule":"Hoje","mentorGuidance":"Proposta solicitada precisa de resposta rápida."},
  {"statusId":"INT-N02","channel":"Internet","family":"Negociação","label":"Proposta enviada — prazo ativo","responsible":"Cliente","temperature":"Quente","objective":"Acompanhar decisão","nextStep":"Programar retorno","cadenceId":"CAD-03","scriptId":"SCR-PROPOSTA-CAD03-T1","potential":"Alto","centralRule":"Retorno vence hoje","mentorGuidance":"Não deixe proposta sem retorno definido."},
  {"statusId":"INT-N03","channel":"Internet","family":"Negociação","label":"Proposta sem retorno","responsible":"Vendedor","temperature":"Quente","objective":"Recuperar decisão","nextStep":"Retomar proposta","cadenceId":"CAD-03","scriptId":"SCR-PROPOSTA-CAD03-T1","potential":"Alto","centralRule":"Hoje","mentorGuidance":"Retome a proposta para descobrir o ponto de trava."},
  {"statusId":"INT-N04","channel":"Internet","family":"Negociação","label":"Negociação ativa — bloqueador não definido","responsible":"Vendedor/Cliente","temperature":"Quente","objective":"Identificar obstáculo","nextStep":"Atualizar o que falta","cadenceId":"Ação imediata","scriptId":"SCR-DECISAO-01","potential":"Muito alto","centralRule":"Hoje","mentorGuidance":"Não deixe 'em negociação' genérico; defina o bloqueador real."},
  {"statusId":"INT-N05","channel":"Internet","family":"Negociação","label":"Objeção de preço","responsible":"Vendedor","temperature":"Quente","objective":"Trabalhar percepção de valor","nextStep":"Entender diferença esperada","cadenceId":"CAD-03","scriptId":"SCR-OBJECAO-PRECO","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Trabalhe valor, não prometa desconto inexistente."},
  {"statusId":"INT-N06","channel":"Internet","family":"Negociação","label":"Objeção de entrada","responsible":"Vendedor","temperature":"Quente","objective":"Buscar viabilidade","nextStep":"Entender entrada possível","cadenceId":"CAD-03","scriptId":"SCR-OBJECAO-ENTRADA","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Descubra qual entrada cabe antes de refazer condição."},
  {"statusId":"INT-N07","channel":"Internet","family":"Negociação","label":"Objeção de parcela","responsible":"Vendedor","temperature":"Quente","objective":"Ajustar estrutura","nextStep":"Entender parcela e prazo viáveis","cadenceId":"CAD-03","scriptId":"SCR-OBJECAO-PARCELA","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Entenda parcela alvo sem prometer aprovação."},
  {"statusId":"INT-N08","channel":"Internet","family":"Negociação","label":"Comparando veículos ou concorrentes","responsible":"Cliente","temperature":"Quente","objective":"Diferenciar solução","nextStep":"Entender critérios de comparação","cadenceId":"CAD-03","scriptId":"SCR-COMPARACAO-01","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Descubra critérios da comparação para reposicionar a solução."},
  {"statusId":"INT-N09","channel":"Internet","family":"Negociação","label":"Aguardando decisão do cliente","responsible":"Cliente","temperature":"Quente","objective":"Recuperar decisão","nextStep":"Follow-up consultivo","cadenceId":"CAD-03","scriptId":"SCR-DECISAO-CAD03-T1","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Pergunte o que pesa na decisão; não cobre resposta vazia."},
  {"statusId":"INT-N10","channel":"Internet","family":"Negociação","label":"Aguardando decisão de terceiro","responsible":"Terceiro","temperature":"Quente","objective":"Envolver decisor","nextStep":"Facilitar participação","cadenceId":"CAD-10","scriptId":"SCR-TERCEIRO-01","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Ajude a envolver quem decide para evitar perda silenciosa."},
  {"statusId":"INT-N11","channel":"Internet","family":"Negociação","label":"Aguardando condição da loja","responsible":"Loja","temperature":"Quente","objective":"Obter resposta interna","nextStep":"Cobrar decisão interna","cadenceId":"CAD-11","scriptId":"SCR-INTERNO","potential":"Muito alto","centralRule":"Verificação interna hoje","mentorGuidance":"Não cobre o cliente enquanto a pendência é interna."},
  {"statusId":"INT-N12","channel":"Internet","family":"Negociação","label":"Pronto para fechamento","responsible":"Vendedor","temperature":"Quente","objective":"Formalizar venda","nextStep":"Confirmar aceite e próximos dados","cadenceId":"Imediata","scriptId":"SCR-FECHAMENTO-01","potential":"Muito alto","centralRule":"Hoje","mentorGuidance":"Não deixe fechamento esfriar; formalize o compromisso."},
  {"statusId":"POR-A01","channel":"Porta","family":"Visita","label":"Atendimento espontâneo em andamento","responsible":"Vendedor","temperature":"Quente","objective":"Realizar atendimento","nextStep":"Diagnosticar e apresentar solução","cadenceId":"Sem cadência","scriptId":"SCR-INTERNO","potential":"Muito alto","centralRule":"Não entra enquanto em atendimento","mentorGuidance":"Atenda e registre apenas o que importa."},
  {"statusId":"POR-A02","channel":"Porta","family":"Visita","label":"Atendimento concluído — desfecho pendente","responsible":"Vendedor","temperature":"Quente","objective":"Registrar resultado","nextStep":"Informar o que aconteceu","cadenceId":"Mesmo dia","scriptId":"SCR-INTERNO","potential":"Muito alto","centralRule":"Hoje","mentorGuidance":"Sem desfecho, a gestão perde a oportunidade."},
  {"statusId":"POR-A03","channel":"Porta","family":"Negociação","label":"Visitou e não comprou","responsible":"Vendedor","temperature":"Quente","objective":"Manter negociação viva","nextStep":"Enviar resumo e retomar conversa","cadenceId":"CAD-03","scriptId":"SCR-POS-VISITA-01","potential":"Alto","centralRule":"Hoje","mentorGuidance":"A visita já aconteceu; agora o foco é recuperar decisão."},
  {"statusId":"POR-A04","channel":"Porta","family":"Negociação","label":"Pós-visita sem resposta","responsible":"Cliente","temperature":"Morno/Quente","objective":"Recuperar oportunidade","nextStep":"Executar tentativa de follow-up","cadenceId":"CAD-03","scriptId":"SCR-POS-VISITA-CAD03-T{n}","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Cliente que visitou tem valor maior que lead frio."},
  {"statusId":"CAR-C01","channel":"Carteira","family":"Contato","label":"Indicação recebida — contato pendente","responsible":"Vendedor","temperature":"Morno","objective":"Iniciar conversa","nextStep":"Abordar mencionando a indicação","cadenceId":"CAD-01","scriptId":"SCR-CAR-INDICACAO-01","potential":"Médio","centralRule":"Próxima ação hoje","mentorGuidance":"Use a indicação como ponte de confiança."},
  {"statusId":"CAR-C02","channel":"Carteira","family":"Contato","label":"Prospecção própria — contato pendente","responsible":"Vendedor","temperature":"Morno","objective":"Iniciar conversa","nextStep":"Executar abordagem de prospecção","cadenceId":"CAD-01","scriptId":"SCR-CAR-PROSPECCAO-01","potential":"Médio","centralRule":"Próxima ação hoje","mentorGuidance":"O motivo real do contato deve estar claro."},
  {"statusId":"CAR-C03","channel":"Carteira","family":"Contato","label":"Cliente antigo — reativação pendente","responsible":"Vendedor","temperature":"Frio/Morno","objective":"Retomar relacionamento","nextStep":"Fazer abordagem de reativação","cadenceId":"CAD-03","scriptId":"SCR-CAR-REATIVACAO-T1","potential":"Médio","centralRule":"Tentativa vence hoje","mentorGuidance":"Retomar histórico antes de tentar vender."},
  {"statusId":"CAR-C04","channel":"Carteira","family":"Contato","label":"Lead antigo acima de 90 dias","responsible":"Vendedor","temperature":"Frio/Morno","objective":"Reativar oportunidade","nextStep":"Retomar com novo contexto","cadenceId":"CAD-03","scriptId":"SCR-CAR-REATIVACAO-T1","potential":"Médio","centralRule":"Tentativa vence hoje","mentorGuidance":"Preserve canalEntrada original e canalVenda Carteira se vender."},
  {"statusId":"CAR-C05","channel":"Carteira","family":"Contato","label":"Contato de anúncio próprio","responsible":"Vendedor","temperature":"Morno","objective":"Iniciar conversa","nextStep":"Responder e qualificar","cadenceId":"CAD-01","scriptId":"SCR-CAR-PROSPECCAO-01","potential":"Médio","centralRule":"Próxima ação hoje","mentorGuidance":"Origem detalhada: marketplace/OLX/tráfego próprio."},
  {"statusId":"CAR-C06","channel":"Carteira","family":"Qualificação","label":"Cliente procurou diretamente o vendedor","responsible":"Vendedor","temperature":"Morno/Quente","objective":"Qualificar intenção","nextStep":"Entender necessidade e prazo","cadenceId":"CAD-04","scriptId":"SCR-QUAL-01","potential":"Médio","centralRule":"Hoje","mentorGuidance":"Aproveite confiança existente para qualificar rápido."},
  {"statusId":"CAR-C07","channel":"Carteira","family":"Relacionamento","label":"Oportunidade de troca ativada","responsible":"Vendedor","temperature":"Morno/Quente","objective":"Criar nova compra","nextStep":"Entender intenção de troca","cadenceId":"CAD-04","scriptId":"SCR-TROCA-FUTURA-01","potential":"Médio","centralRule":"Na data de ativação","mentorGuidance":"Transforme relacionamento em nova oportunidade."},
  {"statusId":"CAR-C08","channel":"Carteira","family":"Relacionamento","label":"Cliente de pós-venda com potencial","responsible":"Vendedor","temperature":"Morno","objective":"Gerar nova oportunidade","nextStep":"Conversar sobre momento atual","cadenceId":"CAD-04","scriptId":"SCR-POSVENDA-01","potential":"Médio","centralRule":"Quando marco vence","mentorGuidance":"Pós-venda bem feito pode gerar indicação ou recompra."},
  {"statusId":"TR-01","channel":"Compartilhado","family":"Troca","label":"Aguardando dados do carro da troca","responsible":"Cliente","temperature":"Quente","objective":"Obter informações","nextStep":"Solicitar placa, versão, ano, km e fotos","cadenceId":"CAD-08","scriptId":"SCR-TROCA-DADOS-T1","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Solicite dados antes de estimar valor."},
  {"statusId":"TR-02","channel":"Compartilhado","family":"Troca","label":"Dados recebidos — avaliação pendente","responsible":"Loja","temperature":"Quente","objective":"Conseguir avaliação","nextStep":"Encaminhar para avaliação","cadenceId":"CAD-11","scriptId":"SCR-INTERNO","potential":"Alto","centralRule":"Verificação interna hoje","mentorGuidance":"A pendência agora é interna, não do cliente."},
  {"statusId":"TR-03","channel":"Compartilhado","family":"Troca","label":"Avaliação presencial necessária","responsible":"Vendedor/Cliente","temperature":"Quente","objective":"Levar veículo à loja","nextStep":"Agendar avaliação presencial","cadenceId":"CAD-02","scriptId":"SCR-VISITA-CAD02-T1","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Agora sim o próximo passo é agendar visita/avaliação."},
  {"statusId":"TR-04","channel":"Compartilhado","family":"Troca","label":"Avaliação em andamento","responsible":"Loja","temperature":"Quente","objective":"Concluir avaliação","nextStep":"Verificar internamente","cadenceId":"CAD-11","scriptId":"SCR-INTERNO","potential":"Alto","centralRule":"Verificação interna hoje","mentorGuidance":"Não cobre o cliente enquanto a loja avalia."},
  {"statusId":"TR-05","channel":"Compartilhado","family":"Troca","label":"Avaliação concluída — valor não apresentado","responsible":"Vendedor","temperature":"Quente","objective":"Apresentar condição","nextStep":"Enviar ou apresentar avaliação","cadenceId":"Hoje","scriptId":"SCR-TROCA-VALOR-01","potential":"Muito alto","centralRule":"Hoje","mentorGuidance":"Valor pronto precisa ser apresentado rapidamente."},
  {"statusId":"TR-06","channel":"Compartilhado","family":"Troca","label":"Valor apresentado — aguardando cliente","responsible":"Cliente","temperature":"Quente","objective":"Conseguir aceite","nextStep":"Retomar decisão da troca","cadenceId":"CAD-03","scriptId":"SCR-TROCA-VALOR-01","potential":"Alto","centralRule":"Retorno vence hoje","mentorGuidance":"Troca pode ser o bloqueador central da venda."},
  {"statusId":"TR-07","channel":"Compartilhado","family":"Troca","label":"Cliente não aceitou a avaliação","responsible":"Vendedor","temperature":"Quente","objective":"Tratar objeção","nextStep":"Entender valor esperado e diferença","cadenceId":"CAD-03","scriptId":"SCR-TROCA-OBJECAO-01","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Entenda a expectativa antes de negociar condição."},
  {"statusId":"TR-08","channel":"Compartilhado","family":"Troca","label":"Troca aprovada","responsible":"Sistema","temperature":"Quente","objective":"Retomar negociação principal","nextStep":"Verificar próximo bloqueador","cadenceId":"Automática","scriptId":"SCR-INTERNO","potential":"Muito alto","centralRule":"Se houver próximo passo hoje","mentorGuidance":"Troca deixou de bloquear. Avance para fechamento ou próxima pendência."},
  {"statusId":"TR-09","channel":"Compartilhado","family":"Troca","label":"Troca inviável","responsible":"Loja/Vendedor","temperature":"Morno/Quente","objective":"Apresentar alternativa","nextStep":"Explicar e oferecer caminho possível","cadenceId":"CAD-03","scriptId":"SCR-TROCA-INVIAVEL-01","potential":"Médio","centralRule":"Tentativa vence hoje","mentorGuidance":"Apresente alternativa sem prometer condição impossível."},
  {"statusId":"FIN-01","channel":"Compartilhado","family":"Financiamento","label":"Simulação pendente","responsible":"Vendedor","temperature":"Quente","objective":"Apresentar condição","nextStep":"Preparar simulação","cadenceId":"Hoje","scriptId":"SCR-FIN-SIMULAR-01","potential":"Alto","centralRule":"Hoje","mentorGuidance":"Simulação pedida exige resposta rápida."},
  {"statusId":"FIN-02","channel":"Compartilhado","family":"Financiamento","label":"Simulação enviada — aguardando cliente","responsible":"Cliente","temperature":"Quente","objective":"Validar condição","nextStep":"Retomar simulação","cadenceId":"CAD-03","scriptId":"SCR-FIN-SIMULACAO-CAD03-T1","potential":"Alto","centralRule":"Retorno vence hoje","mentorGuidance":"Valide entrada/parcela/prazo com cuidado."},
  {"statusId":"FIN-03","channel":"Compartilhado","family":"Financiamento","label":"Documentos para ficha pendentes","responsible":"Cliente","temperature":"Quente","objective":"Completar ficha","nextStep":"Solicitar documentos","cadenceId":"CAD-08","scriptId":"SCR-FIN-DOCUMENTOS-T1","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Peça apenas documentos realmente necessários."},
  {"statusId":"FIN-04","channel":"Compartilhado","family":"Financiamento","label":"Ficha em análise","responsible":"Financeira","temperature":"Quente","objective":"Obter retorno","nextStep":"Verificar análise","cadenceId":"CAD-11","scriptId":"SCR-INTERNO","potential":"Alto","centralRule":"Verificação interna hoje","mentorGuidance":"Pendência é financeira; mantenha cliente informado com base real."},
  {"statusId":"FIN-05","channel":"Compartilhado","family":"Financiamento","label":"Pendência solicitada pela financeira","responsible":"Cliente/Vendedor","temperature":"Quente","objective":"Completar análise","nextStep":"Solicitar pendência","cadenceId":"CAD-08","scriptId":"SCR-FIN-DOCUMENTOS-T1","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"A pendência precisa ser específica e registrada."},
  {"statusId":"FIN-06","channel":"Compartilhado","family":"Financiamento","label":"Financiamento aprovado sem fechamento","responsible":"Vendedor","temperature":"Quente","objective":"Converter aprovação","nextStep":"Conduzir para fechamento","cadenceId":"CAD-09","scriptId":"SCR-FIN-APROVADO-T1","potential":"Muito alto","centralRule":"Hoje","mentorGuidance":"Aprovação reduz barreira. Prioridade alta de fechamento."},
  {"statusId":"FIN-07","channel":"Compartilhado","family":"Financiamento","label":"Aprovado com condição diferente","responsible":"Vendedor","temperature":"Quente","objective":"Reestruturar negociação","nextStep":"Apresentar condição real","cadenceId":"CAD-03","scriptId":"SCR-FIN-CONDICAO-DIFERENTE-01","potential":"Alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Explique condição real sem prometer o que não existe."},
  {"statusId":"FIN-08","channel":"Compartilhado","family":"Financiamento","label":"Financiamento recusado","responsible":"Vendedor","temperature":"Morno","objective":"Avaliar alternativa","nextStep":"Verificar outro caminho autorizado","cadenceId":"Imediata","scriptId":"SCR-FIN-RECUSADO-01","potential":"Médio","centralRule":"Hoje","mentorGuidance":"Tratar com cuidado e buscar alternativas viáveis."},
  {"statusId":"FIN-09","channel":"Compartilhado","family":"Financiamento","label":"Nova simulação necessária","responsible":"Vendedor","temperature":"Quente","objective":"Ajustar estrutura","nextStep":"Refazer simulação","cadenceId":"Hoje","scriptId":"SCR-FIN-SIMULAR-01","potential":"Alto","centralRule":"Hoje","mentorGuidance":"Refazer condição apenas com dados reais."},
  {"statusId":"VEN-01","channel":"Compartilhado","family":"Venda e Entrega","label":"Venda acordada — formalização pendente","responsible":"Vendedor","temperature":"Quente","objective":"Formalizar negócio","nextStep":"Confirmar dados e processo","cadenceId":"Hoje","scriptId":"SCR-FECHAMENTO-01","potential":"Muito alto","centralRule":"Hoje","mentorGuidance":"Formalize para não deixar o aceite esfriar."},
  {"statusId":"VEN-02","channel":"Compartilhado","family":"Venda e Entrega","label":"Sinal pendente","responsible":"Cliente","temperature":"Quente","objective":"Confirmar compromisso","nextStep":"Orientar pagamento do sinal","cadenceId":"CAD-08","scriptId":"SCR-SINAL-01","potential":"Muito alto","centralRule":"Tentativa vence hoje","mentorGuidance":"Sinal pendente precisa de acompanhamento rápido."},
  {"statusId":"VEN-03","channel":"Compartilhado","family":"Venda e Entrega","label":"Sinal recebido — fechamento pendente","responsible":"Loja/Vendedor","temperature":"Quente","objective":"Concluir venda","nextStep":"Finalizar formalização","cadenceId":"Hoje","scriptId":"SCR-INTERNO","potential":"Muito alto","centralRule":"Hoje","mentorGuidance":"Sinal pago aumenta responsabilidade de fechamento."},
  {"statusId":"VEN-04","channel":"Compartilhado","family":"Venda e Entrega","label":"Venda realizada","responsible":"Sistema","temperature":"-","objective":"Registrar resultado","nextStep":"Alimentar funil, faturamento e histórico","cadenceId":"Automática","scriptId":"SCR-INTERNO","potential":"-","centralRule":"Não entra, salvo próximo passo configurado","mentorGuidance":"Venda concluída. Ativar pós-venda se loja usar."},
  {"statusId":"VEN-05","channel":"Compartilhado","family":"Venda e Entrega","label":"Entrega agendada","responsible":"Data/Vendedor","temperature":"-","objective":"Preparar entrega","nextStep":"Aguardar data","cadenceId":"Derivada","scriptId":"SCR-ENTREGA-01","potential":"Médio","centralRule":"Quando data for hoje","mentorGuidance":"Só criar entrega se loja atribui isso ao vendedor."},
  {"statusId":"VEN-06","channel":"Compartilhado","family":"Venda e Entrega","label":"Entrega hoje","responsible":"Vendedor","temperature":"-","objective":"Realizar entrega","nextStep":"Executar entrega","cadenceId":"Central","scriptId":"SCR-ENTREGA-01","potential":"Médio","centralRule":"Hoje","mentorGuidance":"Entrega pode ser oportunidade de relacionamento."},
  {"statusId":"VEN-07","channel":"Compartilhado","family":"Venda e Entrega","label":"Veículo entregue","responsible":"Sistema","temperature":"-","objective":"Iniciar relacionamento","nextStep":"Ativar pós-venda se configurado","cadenceId":"Automática","scriptId":"SCR-POSVENDA-D7","potential":"Médio","centralRule":"Conforme pós-venda","mentorGuidance":"Ativar relacionamento sem obrigar loja que não usa pós-venda."},
  {"statusId":"PER-01","channel":"Compartilhado","family":"Perda e Futuro","label":"Motivo da perda pendente","responsible":"Vendedor","temperature":"-","objective":"Qualificar perda","nextStep":"Registrar motivo","cadenceId":"Hoje","scriptId":"SCR-INTERNO","potential":"Baixo","centralRule":"Hoje","mentorGuidance":"Sem motivo de perda, a carteira perde inteligência."},
  {"statusId":"PER-02","channel":"Compartilhado","family":"Perda e Futuro","label":"Venda perdida","responsible":"Encerrado","temperature":"-","objective":"Preservar inteligência","nextStep":"Encerrar oportunidade","cadenceId":"Sem cadência","scriptId":"SCR-INTERNO","potential":"Baixo","centralRule":"Não entra","mentorGuidance":"Perda qualificada pode virar oportunidade futura."},
  {"statusId":"PER-03","channel":"Compartilhado","family":"Perda e Futuro","label":"Cadência encerrada sem resposta","responsible":"Encerrado","temperature":"Frio","objective":"Preservar cliente","nextStep":"Retirar da Carteira Ativa","cadenceId":"Sem ação","scriptId":"SCR-INTERNO","potential":"Baixo","centralRule":"Não entra","mentorGuidance":"Não é perda automática; vira base para Plano de Ataque."},
  {"statusId":"PER-04","channel":"Compartilhado","family":"Perda e Futuro","label":"Contato inválido encerrado","responsible":"Encerrado","temperature":"-","objective":"Evitar esforço improdutivo","nextStep":"Encerrar","cadenceId":"Sem cadência","scriptId":"SCR-INTERNO","potential":"Baixo","centralRule":"Não entra","mentorGuidance":"Preservar histórico e evitar novas tentativas inúteis."},
  {"statusId":"PER-05","channel":"Compartilhado","family":"Perda e Futuro","label":"Contato futuro programado","responsible":"Data","temperature":"Frio/Morno","objective":"Retomar no momento certo","nextStep":"Aguardar data","cadenceId":"CAD-12","scriptId":"SCR-FUTURO-01","potential":"Baixo","centralRule":"Quando data chegar","mentorGuidance":"A carteira deve lembrar no momento certo."},
  {"statusId":"PER-06","channel":"Compartilhado","family":"Perda e Futuro","label":"Oportunidade transferida para Carteira","responsible":"Sistema","temperature":"Frio/Morno","objective":"Reconhecer ação futura do vendedor","nextStep":"Criar nova oportunidade Carteira","cadenceId":"Automática","scriptId":"SCR-CAR-REATIVACAO-T1","potential":"Médio","centralRule":"Quando reativado","mentorGuidance":"Preservar canalEntrada e calcular canalVenda Carteira se vender."},
  {"statusId":"REL-01","channel":"Compartilhado","family":"Relacionamento","label":"Pós-venda D+7","responsible":"Vendedor","temperature":"-","objective":"Verificar satisfação","nextStep":"Fazer contato e pedir indicação","cadenceId":"CAD-13","scriptId":"SCR-POSVENDA-D7","potential":"Médio","centralRule":"Quando marco vence","mentorGuidance":"Relacionamento bem feito gera indicação."},
  {"statusId":"REL-02","channel":"Compartilhado","family":"Relacionamento","label":"Pós-venda D+30","responsible":"Vendedor","temperature":"-","objective":"Confirmar adaptação","nextStep":"Fazer contato","cadenceId":"CAD-13","scriptId":"SCR-POSVENDA-D30","potential":"Médio","centralRule":"Quando marco vence","mentorGuidance":"Manter relacionamento após compra."},
  {"statusId":"REL-03","channel":"Compartilhado","family":"Relacionamento","label":"Relacionamento D+180","responsible":"Vendedor","temperature":"-","objective":"Manter proximidade","nextStep":"Fazer contato leve","cadenceId":"CAD-13","scriptId":"SCR-POSVENDA-D180","potential":"Baixo","centralRule":"Quando marco vence","mentorGuidance":"Cliente antigo bem acompanhado vira Carteira."},
  {"statusId":"REL-04","channel":"Compartilhado","family":"Relacionamento","label":"Troca potencial em 12 meses","responsible":"Vendedor","temperature":"Morno","objective":"Identificar intenção","nextStep":"Conversar sobre ciclo de troca","cadenceId":"CAD-13","scriptId":"SCR-TROCA-12M","potential":"Médio","centralRule":"Quando marco vence","mentorGuidance":"Começar a preparar futura troca."},
  {"statusId":"REL-05","channel":"Compartilhado","family":"Relacionamento","label":"Oferta de troca em 18 meses","responsible":"Vendedor","temperature":"Morno/Quente","objective":"Criar oportunidade","nextStep":"Apresentar possibilidade de upgrade","cadenceId":"CAD-13","scriptId":"SCR-TROCA-18M","potential":"Médio","centralRule":"Quando marco vence","mentorGuidance":"Relacionamento vira nova venda."},
  {"statusId":"REL-06","channel":"Compartilhado","family":"Relacionamento","label":"Recompra ou troca em 24 meses","responsible":"Vendedor","temperature":"Morno/Quente","objective":"Gerar nova compra","nextStep":"Reabrir oportunidade","cadenceId":"CAD-13","scriptId":"SCR-TROCA-24M","potential":"Alto","centralRule":"Quando marco vence","mentorGuidance":"Momento ideal para nova oportunidade de Carteira."},
  {"statusId":"REL-07","channel":"Compartilhado","family":"Relacionamento","label":"Garantia aberta","responsible":"Vendedor/Loja","temperature":"-","objective":"Proteger relacionamento","nextStep":"Confirmar recebimento e orientar","cadenceId":"CAD-11","scriptId":"SCR-GARANTIA-01","potential":"Médio","centralRule":"Quando acompanhamento vence","mentorGuidance":"Garantia é relação sensível, não apenas operação."},
  {"statusId":"REL-08","channel":"Compartilhado","family":"Relacionamento","label":"Garantia em acompanhamento","responsible":"Loja/Vendedor","temperature":"-","objective":"Manter cliente informado","nextStep":"Verificar andamento","cadenceId":"CAD-11","scriptId":"SCR-GARANTIA-01","potential":"Médio","centralRule":"Quando acompanhamento vence","mentorGuidance":"Cliente precisa sentir acompanhamento."},
  {"statusId":"REL-09","channel":"Compartilhado","family":"Relacionamento","label":"Garantia resolvida","responsible":"Vendedor","temperature":"-","objective":"Recuperar confiança","nextStep":"Confirmar satisfação","cadenceId":"Hoje","scriptId":"SCR-GARANTIA-RESOLVIDA","potential":"Médio","centralRule":"Hoje","mentorGuidance":"Feche o ciclo de garantia com relacionamento."},
] as const

const PORT_INDEX = new Map(STATUS_CATALOG.map((s) => [s.statusId, s]))

export function statusPorId(statusId: string | null | undefined): StatusCatalogEntry | null {
  if (!statusId) return null
  return PORT_INDEX.get(statusId) ?? null
}

export type ScriptCatalogEntry = {
  scriptId: string
  area: string | null
  attempt: string | null
  objective: string | null
  body: string
}

export const SCRIPT_CATALOG: readonly ScriptCatalogEntry[] = [
  {"scriptId":"SCR-INT-CAD01-T1","area":"Internet","attempt":"Tentativa 1","objective":"Iniciar conversa","body":"Oi, {nome}! Tudo bem?\r\n\r\nAqui é {vendedor}, da {loja}. Vi seu interesse no {veiculo} e quero te ajudar com as informações certas.\r\n\r\nVocê pensa em comprar agora ou ainda está pesquisando opções?"},
  {"scriptId":"SCR-INT-CAD01-T2","area":"Internet","attempt":"Tentativa 2","objective":"Confirmar interesse","body":"Oi, {nome}! Só confirmando se recebeu minha mensagem sobre o {veiculo}.\r\n\r\nQual informação te ajuda mais neste momento: valor, condições, troca ou financiamento?"},
  {"scriptId":"SCR-INT-CAD01-T3","area":"Internet","attempt":"Tentativa 3","objective":"Facilitar resposta","body":"{nome}, para eu ser mais objetivo: você já definiu o veículo ou ainda está comparando algumas opções?\r\n\r\nPosso te ajudar a filtrar o que faz mais sentido."},
  {"scriptId":"SCR-INT-CAD01-T4","area":"Internet","attempt":"Tentativa 4","objective":"Abrir alternativa","body":"Posso te explicar tudo por aqui ou separar um horário para você conhecer melhor o {veiculo}.\r\n\r\nQual formato fica mais fácil para você?"},
  {"scriptId":"SCR-INT-CAD01-T5","area":"Internet","attempt":"Tentativa 5","objective":"Pedir permissão para seguir","body":"Oi, {nome}! Ainda faz sentido eu acompanhar sua busca pelo {veiculo}?\r\n\r\nSe o momento mudou, posso deixar registrado para falar com você mais adiante."},
  {"scriptId":"SCR-INT-CAD01-T6","area":"Internet","attempt":"Tentativa 6","objective":"Encerrar cadência respeitosamente","body":"Vou encerrar este acompanhamento por agora para não insistir.\r\n\r\nQuando quiser retomar a busca pelo {veiculo}, pode me chamar por aqui. Ficarei à disposição."},
  {"scriptId":"SCR-CAR-INDICACAO-01","area":"Carteira","attempt":"Inicial","objective":"Iniciar conversa por indicação","body":"Oi, {nome}! Tudo bem?\r\n\r\nSou {vendedor}, da {loja}. O {nomeIndicador} comentou que você está avaliando a compra ou troca de um veículo.\r\n\r\nPosso entender melhor o que você procura e te ajudar?"},
  {"scriptId":"SCR-CAR-PROSPECCAO-01","area":"Carteira","attempt":"Inicial","objective":"Prospecção direta","body":"Oi, {nome}! Tudo bem?\r\n\r\nAqui é {vendedor}. Estou entrando em contato porque {motivoRealDoContato}.\r\n\r\nVocê pensa em comprar ou trocar de veículo agora ou está se planejando para mais adiante?"},
  {"scriptId":"SCR-CAR-REATIVACAO-T1","area":"Carteira","attempt":"Tentativa 1","objective":"Reativar relacionamento","body":"Oi, {nome}! Tudo bem?\r\n\r\nEstou atualizando meus acompanhamentos e queria saber se a ideia de comprar ou trocar de veículo ainda está nos seus planos.\r\n\r\nSe fizer sentido, posso retomar sua busca e te ajudar com as opções atuais."},
  {"scriptId":"SCR-CAR-REATIVACAO-T2","area":"Carteira","attempt":"Tentativa 2","objective":"Atualizar necessidade","body":"{nome}, seu interesse continua relacionado ao {veiculo} ou sua necessidade mudou?\r\n\r\nCom essa informação consigo te orientar melhor."},
  {"scriptId":"SCR-CAR-REATIVACAO-T3","area":"Carteira","attempt":"Tentativa 3","objective":"Descobrir barreira","body":"Hoje, o que seria mais importante para você retomar essa compra: veículo, valor, entrada, parcela ou troca?"},
  {"scriptId":"SCR-CAR-REATIVACAO-T4","area":"Carteira","attempt":"Tentativa 4","objective":"Oferecer opções","body":"Posso separar algumas opções alinhadas ao que você procura e te mostrar sem compromisso.\r\n\r\nAinda faz sentido?"},
  {"scriptId":"SCR-CAR-REATIVACAO-T5","area":"Carteira","attempt":"Tentativa 5","objective":"Programar futuro","body":"A compra ficou para outro momento?\r\n\r\nPosso deixar uma data registrada para te procurar quando fizer mais sentido."},
  {"scriptId":"SCR-CAR-REATIVACAO-T6","area":"Carteira","attempt":"Tentativa 6","objective":"Pausar acompanhamento","body":"Vou pausar este acompanhamento por agora.\r\n\r\nQuando decidir retomar a compra ou troca, me chame por aqui e continuamos de onde paramos."},
  {"scriptId":"SCR-QUAL-01","area":"Qualificação","attempt":"Uso e necessidade","objective":"Entender necessidade","body":"Para eu te orientar melhor, {nome}: você procura esse veículo para uso pessoal, família ou trabalho?"},
  {"scriptId":"SCR-QUAL-02","area":"Qualificação","attempt":"Prazo","objective":"Entender timing","body":"Você pensa em comprar agora, nos próximos dias ou está se planejando para mais adiante?"},
  {"scriptId":"SCR-QUAL-03","area":"Qualificação","attempt":"Troca e financiamento","objective":"Entender viabilidade","body":"Você pretende colocar algum veículo na troca?\r\n\r\nE pensa em pagamento à vista ou financiamento?"},
  {"scriptId":"SCR-QUAL-04","area":"Qualificação","attempt":"Confirmação","objective":"Consolidar qualificação","body":"Entendi. Então você procura {resumoNecessidade}.\r\n\r\nO próximo passo que mais faz sentido é você conhecer as opções pessoalmente. Posso organizar um horário?"},
  {"scriptId":"SCR-VISITA-CAD02-T1","area":"Visita","attempt":"Tentativa 1","objective":"Convidar para visita","body":"{nome}, para decidir com mais segurança, o ideal é conhecer o {veiculo} pessoalmente.\r\n\r\nTenho disponibilidade para te atender {opcao1} ou {opcao2}. Qual fica melhor?"},
  {"scriptId":"SCR-VISITA-CAD02-T2","area":"Visita","attempt":"Tentativa 2","objective":"Reforçar benefício","body":"Na visita você consegue analisar o carro com calma e esclarecer os pontos da negociação.\r\n\r\nQual dia ou período costuma ser mais fácil para você?"},
  {"scriptId":"SCR-VISITA-CAD02-T3","area":"Visita","attempt":"Tentativa 3","objective":"Facilitar agenda","body":"Você prefere vir durante a semana ou no sábado?\r\n\r\nCom isso consigo sugerir um horário mais confortável."},
  {"scriptId":"SCR-VISITA-CAD02-T4","area":"Visita","attempt":"Tentativa 4","objective":"Entender barreira","body":"O que está dificultando sua visita neste momento: horário, distância ou ainda está decidindo sobre o veículo?"},
  {"scriptId":"SCR-VISITA-CAD02-T5","area":"Visita","attempt":"Tentativa 5","objective":"Atendimento objetivo","body":"Posso organizar um atendimento objetivo, focado exatamente no que você precisa avaliar.\r\n\r\nAinda faz sentido marcarmos?"},
  {"scriptId":"SCR-VISITA-CAD02-T6","area":"Visita","attempt":"Tentativa 6","objective":"Deixar em aberto","body":"Vou deixar a visita em aberto por agora.\r\n\r\nQuando tiver um melhor momento, me avise e organizo o atendimento para você."},
  {"scriptId":"SCR-VISITA-DATA-T1","area":"Visita","attempt":"Definir data","objective":"Converter aceite em data/hora","body":"{nome}, consigo te atender {opcao1} ou {opcao2} para você conhecer o {veiculo}. Qual desses horários fica melhor?"},
  {"scriptId":"SCR-CONFIRMAR-D2","area":"Confirmação","attempt":"D-2","objective":"Preparar confirmação","body":"Oi, {nome}! Sua visita para conhecer o {veiculo} está prevista para {data}, às {hora}.\r\n\r\nPosso manter esse horário? Se precisar ajustar, me avise."},
  {"scriptId":"SCR-CONFIRMAR-D1","area":"Confirmação","attempt":"D-1","objective":"Confirmar presença","body":"Oi, {nome}! Confirmando nosso encontro amanhã, às {hora}, para você conhecer o {veiculo}.\r\n\r\nEstá tudo certo para você?"},
  {"scriptId":"SCR-CONFIRMAR-D0","area":"Confirmação","attempt":"D0","objective":"Lembrete final","body":"Bom dia, {nome}! Te aguardo hoje às {hora}.\r\n\r\nQuando estiver a caminho, pode me avisar por aqui."},
  {"scriptId":"SCR-VISITA-HOJE","area":"Visita","attempt":"D0","objective":"Recepcionar","body":"Bom dia, {nome}! Tudo certo para sua visita hoje às {hora}?\r\n\r\nVou deixar o {veiculo} separado para te atender bem."},
  {"scriptId":"SCR-NAO-COMPARECEU-T1","area":"Não compareceu","attempt":"Tentativa 1","objective":"Recuperar visita","body":"Oi, {nome}! Vi que hoje não conseguimos nos encontrar.\r\n\r\nSem problema. Ainda faz sentido você conhecer o {veiculo}?"},
  {"scriptId":"SCR-NAO-COMPARECEU-T2","area":"Não compareceu","attempt":"Tentativa 2","objective":"Reagendar","body":"Posso reorganizar sua visita para outro horário.\r\n\r\nVocê prefere durante a semana ou no sábado?"},
  {"scriptId":"SCR-NAO-COMPARECEU-T3","area":"Não compareceu","attempt":"Tentativa 3","objective":"Descobrir motivo","body":"Seu plano de compra mudou ou foi apenas uma dificuldade de horário?"},
  {"scriptId":"SCR-NAO-COMPARECEU-T4","area":"Não compareceu","attempt":"Tentativa 4","objective":"Oferecer atendimento objetivo","body":"Tenho como organizar um atendimento mais rápido e objetivo.\r\n\r\nQual período seria mais fácil para você?"},
  {"scriptId":"SCR-NAO-COMPARECEU-T5","area":"Não compareceu","attempt":"Tentativa 5","objective":"Deixar em aberto","body":"Vou deixar o reagendamento em aberto.\r\n\r\nQuando puder retomar, me avise e organizo para você."},
  {"scriptId":"SCR-POS-VISITA-01","area":"Porta/Pós-visita","attempt":"Inicial","objective":"Retomar pós-visita","body":"Oi, {nome}! Foi um prazer te atender hoje.\r\n\r\nQuero continuar te ajudando em relação ao {veiculo}. Qual ponto ficou mais importante para sua decisão: valor, troca, entrada, parcela ou ainda comparar outras opções?"},
  {"scriptId":"SCR-PROPOSTA-ENVIAR","area":"Proposta","attempt":"Envio","objective":"Enviar proposta","body":"{nome}, conforme conversamos, vou te enviar as condições registradas para o {veiculo}.\r\n\r\nDepois me diga qual ponto fica mais importante para avançarmos."},
  {"scriptId":"SCR-PROPOSTA-CAD03-T1","area":"Proposta","attempt":"Tentativa 1","objective":"Retomar proposta","body":"Oi, {nome}! Conseguiu analisar a proposta do {veiculo}?\r\n\r\nQuero entender se existe algum ponto que ainda precisa ser ajustado ou esclarecido."},
  {"scriptId":"SCR-PROPOSTA-CAD03-T2","area":"Proposta","attempt":"Tentativa 2","objective":"Identificar objeção","body":"O que mais pesou na sua análise: valor final, entrada, parcela, troca ou outro ponto?"},
  {"scriptId":"SCR-PROPOSTA-CAD03-T3","area":"Proposta","attempt":"Tentativa 3","objective":"Revisar negociação","body":"Posso revisar a negociação com você usando apenas as condições realmente disponíveis.\r\n\r\nQual seria o cenário mais viável para avançarmos?"},
  {"scriptId":"SCR-PROPOSTA-CAD03-T4","area":"Proposta","attempt":"Tentativa 4","objective":"Confirmar continuidade","body":"Ainda faz sentido continuar trabalhando essa negociação ou seu momento de compra mudou?"},
  {"scriptId":"SCR-PROPOSTA-CAD03-T5","area":"Proposta","attempt":"Tentativa 5","objective":"Programar retorno","body":"Posso programar um retorno para uma data mais adequada, sem ficar insistindo agora.\r\n\r\nQuando seria melhor?"},
  {"scriptId":"SCR-PROPOSTA-CAD03-T6","area":"Proposta","attempt":"Tentativa 6","objective":"Pausar negociação","body":"Vou pausar esta negociação por agora.\r\n\r\nSe quiser retomar as condições do {veiculo}, me chame e seguimos de onde paramos."},
  {"scriptId":"SCR-OBJECAO-PRECO","area":"Objeção","attempt":"Preço","objective":"Entender diferença","body":"Entendi, {nome}. Quando falamos de valor, qual diferença ficou impedindo o avanço?\r\n\r\nAssim consigo entender se existe algum caminho real para trabalharmos."},
  {"scriptId":"SCR-OBJECAO-ENTRADA","area":"Objeção","attempt":"Entrada","objective":"Entender entrada possível","body":"Para eu te orientar melhor: qual entrada ficaria mais confortável para você neste momento?"},
  {"scriptId":"SCR-OBJECAO-PARCELA","area":"Objeção","attempt":"Parcela","objective":"Entender parcela alvo","body":"Qual parcela ficaria mais confortável para você analisar com segurança? Com isso consigo verificar se existe algum caminho possível."},
  {"scriptId":"SCR-COMPARACAO-01","area":"Comparação","attempt":"Concorrente/outro veículo","objective":"Diferenciar solução","body":"Entendo que você esteja comparando opções. O que está pesando mais na comparação: preço, condição, estado do veículo, garantia ou confiança na loja?"},
  {"scriptId":"SCR-DECISAO-CAD03-T1","area":"Decisão","attempt":"Follow-up","objective":"Descobrir objeção real","body":"Entendo, {nome}.\r\n\r\nSó para eu te ajudar melhor: o que ficou pesando mais na sua decisão?\r\n\r\nValor, entrada, parcela, troca ou ainda está comparando outras opções?"},
  {"scriptId":"SCR-TERCEIRO-01","area":"Decisão de terceiro","attempt":"Envolver decisor","objective":"Facilitar participação","body":"Entendi, {nome}. Para a decisão ficar mais segura, podemos envolver {tipoDecisor} na conversa ou organizar uma visita juntos.\r\n\r\nQual opção seria mais fácil?"},
  {"scriptId":"SCR-TROCA-DADOS-T1","area":"Troca","attempt":"Dados pendentes","objective":"Solicitar dados da troca","body":"Para avançarmos na avaliação do seu veículo, preciso destas informações:\r\n\r\n- placa;\r\n- modelo e versão;\r\n- ano;\r\n- quilometragem;\r\n- fotos externas e internas.\r\n\r\nConsegue me enviar?"},
  {"scriptId":"SCR-TROCA-DADOS-T2","area":"Troca","attempt":"Reforço","objective":"Relembrar pendência","body":"Oi, {nome}! Ficaram pendentes os dados do seu veículo para conseguirmos avançar na avaliação.\r\n\r\nPode me enviar quando tiver um momento?"},
  {"scriptId":"SCR-TROCA-DADOS-T3","area":"Troca","attempt":"Importância","objective":"Explicar necessidade","body":"Essas informações são importantes para evitar uma estimativa sem base.\r\n\r\nAssim que receber, encaminho para a avaliação."},
  {"scriptId":"SCR-TROCA-DADOS-T4","area":"Troca","attempt":"Alternativa","objective":"Avaliação presencial","body":"Ainda pretende utilizar seu veículo na troca?\r\n\r\nSe preferir, também podemos organizar uma avaliação presencial."},
  {"scriptId":"SCR-TROCA-VALOR-01","area":"Troca","attempt":"Valor apresentado","objective":"Retomar decisão da troca","body":"{nome}, a avaliação do seu veículo ficou em {valorAvaliacao}.\r\n\r\nQuero entender se essa condição ficou próxima do que você esperava ou se existe uma diferença que precisamos analisar."},
  {"scriptId":"SCR-TROCA-OBJECAO-01","area":"Troca","attempt":"Objeção valor","objective":"Entender expectativa","body":"Entendo, {nome}. Qual valor você esperava no seu veículo?\r\n\r\nCom essa diferença clara, consigo entender melhor se existe algum caminho para continuar a negociação."},
  {"scriptId":"SCR-TROCA-INVIAVEL-01","area":"Troca","attempt":"Inviável","objective":"Apresentar alternativa","body":"{nome}, neste formato não conseguimos seguir com seu veículo na troca.\r\n\r\nPosso te explicar o motivo e verificar uma alternativa para mantermos a negociação?"},
  {"scriptId":"SCR-FIN-SIMULAR-01","area":"Financiamento","attempt":"Simulação","objective":"Coletar dados para simular","body":"Para eu montar uma simulação mais próxima do seu cenário, você pensa em qual valor de entrada e prazo?"},
  {"scriptId":"SCR-FIN-SIMULACAO-CAD03-T1","area":"Financiamento","attempt":"Simulação enviada","objective":"Validar condição","body":"{nome}, conseguiu avaliar a simulação enviada?\r\n\r\nO que ficou mais importante para ajustar: entrada, parcela ou prazo?"},
  {"scriptId":"SCR-FIN-DOCUMENTOS-T1","area":"Financiamento","attempt":"Documentos","objective":"Solicitar pendências","body":"Para avançarmos com a análise, ficaram pendentes os seguintes dados ou documentos:\r\n\r\n{listaPendencias}\r\n\r\nQuando conseguir enviar, dou continuidade à ficha."},
  {"scriptId":"SCR-FIN-APROVADO-T1","area":"Financiamento","attempt":"Aprovado","objective":"Converter aprovação","body":"Boa notícia, {nome}: seu financiamento foi aprovado nas condições registradas.\r\n\r\nAgora precisamos revisar os detalhes e confirmar se podemos seguir com o fechamento."},
  {"scriptId":"SCR-FIN-APROVADO-T2","area":"Financiamento","attempt":"Aprovado 2","objective":"Revisar condição","body":"Conseguiu analisar a condição aprovada?\r\n\r\nQual ponto precisa ser esclarecido para avançarmos?"},
  {"scriptId":"SCR-FIN-APROVADO-T3","area":"Financiamento","attempt":"Aprovado 3","objective":"Alinhar estrutura","body":"A aprovação resolveu a parte do crédito. Falta entendermos se entrada, parcela e veículo ficaram alinhados.\r\n\r\nPodemos revisar juntos?"},
  {"scriptId":"SCR-FIN-APROVADO-T4","area":"Financiamento","attempt":"Aprovado 4","objective":"Confirmar continuidade","body":"A condição aprovada ainda faz sentido ou seu cenário mudou?\r\n\r\nPreciso dessa confirmação para definir o próximo passo."},
  {"scriptId":"SCR-FIN-CONDICAO-DIFERENTE-01","area":"Financiamento","attempt":"Condição diferente","objective":"Apresentar condição real","body":"{nome}, a financeira retornou com uma condição diferente da simulação inicial.\r\n\r\nPosso te explicar com clareza o que mudou e avaliar se ainda faz sentido para você?"},
  {"scriptId":"SCR-FIN-RECUSADO-01","area":"Financiamento","attempt":"Recusado","objective":"Avaliar alternativa","body":"{nome}, a análise não voltou aprovada neste formato.\r\n\r\nPosso verificar se existe alguma alternativa autorizada para continuarmos ou se é melhor programarmos outro momento."},
  {"scriptId":"SCR-FECHAMENTO-01","area":"Fechamento","attempt":"Formalização","objective":"Formalizar venda","body":"{nome}, estamos alinhados para avançar com o {veiculo}.\r\n\r\nVou te orientar nos próximos dados para formalizarmos a venda."},
  {"scriptId":"SCR-SINAL-01","area":"Sinal","attempt":"Pagamento","objective":"Orientar sinal","body":"{nome}, para garantir o andamento da venda, falta apenas o sinal conforme combinado.\r\n\r\nPosso te orientar com o próximo passo?"},
  {"scriptId":"SCR-ENTREGA-01","area":"Entrega","attempt":"Entrega","objective":"Confirmar entrega","body":"Oi, {nome}! Confirmando a entrega do {veiculo} para {data} às {hora}.\r\n\r\nEstá tudo certo para você?"},
  {"scriptId":"SCR-FUTURO-01","area":"Futuro","attempt":"Programado","objective":"Preservar oportunidade","body":"Perfeito, {nome}. Vou deixar registrado para te procurar em {dataRetorno}.\r\n\r\nAssim retomamos no momento mais adequado para você."},
  {"scriptId":"SCR-POSVENDA-D7","area":"Pós-venda","attempt":"D+7","objective":"Satisfação e indicação","body":"Oi, {nome}! Tudo bem com o {veiculo}?\r\n\r\nQuero saber se está tudo certo e como foram esses primeiros dias.\r\n\r\nSe lembrar de alguém que também esteja procurando carro, pode me indicar. Vou atender com o mesmo cuidado."},
  {"scriptId":"SCR-POSVENDA-D30","area":"Pós-venda","attempt":"D+30","objective":"Adaptação","body":"Oi, {nome}! Como está sua adaptação ao {veiculo}?\r\n\r\nPassando para confirmar se está tudo bem e me colocar à disposição."},
  {"scriptId":"SCR-POSVENDA-D180","area":"Pós-venda","attempt":"D+180","objective":"Relacionamento","body":"Oi, {nome}! Tudo bem?\r\n\r\nPassando para manter contato e saber como está sua experiência com o {veiculo}."},
  {"scriptId":"SCR-TROCA-12M","area":"Pós-venda","attempt":"12 meses","objective":"Investigar intenção de troca","body":"Oi, {nome}! Já passou aproximadamente um ano desde a compra do {veiculo}.\r\n\r\nVocê pretende permanecer com ele por mais tempo ou já começa a considerar uma futura troca?"},
  {"scriptId":"SCR-TROCA-18M","area":"Pós-venda","attempt":"18 meses","objective":"Oferta de troca","body":"Oi, {nome}! Tudo bem?\r\n\r\nQuero entender se já faz sentido avaliarmos uma possibilidade de troca ou upgrade do seu {veiculo}."},
  {"scriptId":"SCR-TROCA-24M","area":"Pós-venda","attempt":"24 meses","objective":"Recompra ou troca","body":"Oi, {nome}! Seu ciclo com o {veiculo} já permite avaliarmos uma possível recompra ou troca.\r\n\r\nQuer que eu faça uma análise inicial?"},
  {"scriptId":"SCR-GARANTIA-01","area":"Garantia","attempt":"Acompanhamento","objective":"Proteger relacionamento","body":"Oi, {nome}! Estou acompanhando a situação do seu veículo.\r\n\r\nQuero confirmar se houve alguma atualização e garantir que você continue informado até a resolução."},
  {"scriptId":"SCR-GARANTIA-RESOLVIDA","area":"Garantia","attempt":"Resolvida","objective":"Confirmar satisfação","body":"Oi, {nome}! A situação do seu veículo foi resolvida.\r\n\r\nQuero confirmar se ficou tudo certo e se posso ajudar em mais alguma coisa."},
  {"scriptId":"SCR-INTERNO","area":"Interno","attempt":"Não enviar ao cliente","objective":"Registro interno","body":"Ação interna. Não enviar mensagem ao cliente sem informação confirmada."},
] as const

const SCRIPT_INDEX = new Map(SCRIPT_CATALOG.map((s) => [s.scriptId, s]))

export function scriptPorId(scriptId: string | null | undefined): ScriptCatalogEntry | null {
  if (!scriptId) return null
  return SCRIPT_INDEX.get(scriptId) ?? null
}

export const SCRIPT_IDS: ReadonlySet<string> = new Set(SCRIPT_CATALOG.map((s) => s.scriptId))
