-- Forward-only recovery for relations whose historical create migrations may
-- have run after their original hardening migration.
--
-- The IF NOT EXISTS guards make this safe for preview branches with either
-- relation missing. The grants and policies are reapplied idempotently so an
-- existing relation cannot retain the weaker state that caused the ordering
-- gap.

BEGIN;

CREATE TABLE IF NOT EXISTS public.data_correction_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  correction_key text NOT NULL,
  table_name text NOT NULL,
  row_identity jsonb NOT NULL DEFAULT '{}'::jsonb,
  payload jsonb NOT NULL,
  action text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.backup_is_venda_loja_20260805 (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

ALTER TABLE public.data_correction_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.data_correction_audit FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.data_correction_audit TO service_role;
DO $$
BEGIN
  IF to_regclass('public.data_correction_audit_id_seq') IS NOT NULL THEN
    EXECUTE 'GRANT USAGE, SELECT ON SEQUENCE public.data_correction_audit_id_seq TO service_role';
  END IF;
END;
$$;
DROP POLICY IF EXISTS "service_role_manage_data_correction_audit"
  ON public.data_correction_audit;
CREATE POLICY "service_role_manage_data_correction_audit"
  ON public.data_correction_audit
  FOR ALL TO service_role
  USING (true)
  WITH CHECK (true);

ALTER TABLE public.backup_is_venda_loja_20260805 ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.backup_is_venda_loja_20260805 FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.backup_is_venda_loja_20260805 TO service_role;
DO $$
BEGIN
  IF to_regclass('public.backup_is_venda_loja_20260805_id_seq') IS NOT NULL THEN
    EXECUTE 'GRANT USAGE, SELECT ON SEQUENCE public.backup_is_venda_loja_20260805_id_seq TO service_role';
  END IF;
END;
$$;
DROP POLICY IF EXISTS "deny_api_backup_is_venda_loja_20260805"
  ON public.backup_is_venda_loja_20260805;
CREATE POLICY "deny_api_backup_is_venda_loja_20260805"
  ON public.backup_is_venda_loja_20260805
  FOR ALL TO anon, authenticated
  USING (false)
  WITH CHECK (false);

COMMIT;

-- DOWN (compensatory): do not drop either relation or reopen API grants.
-- Any rollback requires an incident-approved replacement migration that keeps
-- the audit and recovery data protected.
