-- Preview branches without data may not contain the historical backup table.
-- Keep the relation available for the following security/comment migration.
CREATE TABLE IF NOT EXISTS public.backup_is_venda_loja_20260805 (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

-- DOWN
-- No-op by design: never drop a backup relation or its recovery data.
