-- Ensure the audit relation exists before 20260805120000 hardens its grants.
-- Some preview branches were created without this relation even though the
-- generated database contract and production security inventory include it.
CREATE TABLE IF NOT EXISTS public.data_correction_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  correction_key text NOT NULL,
  table_name text NOT NULL,
  row_identity jsonb NOT NULL DEFAULT '{}'::jsonb,
  payload jsonb NOT NULL,
  action text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- DOWN
-- No-op by design: do not drop an existing audit table or its recorded data.
