-- Preview branches without data may not contain the historical backup table.
-- Keep the relation available and inaccessible to API roles.
BEGIN;

CREATE TABLE IF NOT EXISTS public.backup_is_venda_loja_20260805 (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

ALTER TABLE public.backup_is_venda_loja_20260805 ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.backup_is_venda_loja_20260805 FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.backup_is_venda_loja_20260805_id_seq
  FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.backup_is_venda_loja_20260805 TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.backup_is_venda_loja_20260805_id_seq TO service_role;
DROP POLICY IF EXISTS "deny_api_backup_is_venda_loja_20260805"
  ON public.backup_is_venda_loja_20260805;
CREATE POLICY "deny_api_backup_is_venda_loja_20260805"
  ON public.backup_is_venda_loja_20260805
  AS RESTRICTIVE
  FOR ALL TO anon, authenticated
  USING (false)
  WITH CHECK (false);

COMMIT;

-- DOWN
-- No-op by design: never drop a backup relation or its recovery data.
