-- Ensure the audit relation is protected before any later migration can use it.
-- Some preview branches were created without this relation even though the
-- generated database contract and production security inventory include it.
BEGIN;

CREATE TABLE IF NOT EXISTS public.data_correction_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  correction_key text NOT NULL,
  table_name text NOT NULL,
  row_identity jsonb NOT NULL DEFAULT '{}'::jsonb,
  payload jsonb NOT NULL,
  action text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.data_correction_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.data_correction_audit FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.data_correction_audit TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.data_correction_audit_id_seq TO service_role;
DROP POLICY IF EXISTS "service_role_manage_data_correction_audit"
  ON public.data_correction_audit;
CREATE POLICY "service_role_manage_data_correction_audit"
  ON public.data_correction_audit
  FOR ALL TO service_role
  USING (true)
  WITH CHECK (true);

COMMIT;

-- DOWN
-- No-op by design: do not drop an existing audit table or its recorded data.
